#Name: 1Remover.zs
#Author: Austinsupercar

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Conditions;
import loottweaker.vanilla.loot.Functions;

print("Initializing '1Remover'...");

mods.ltt.LootTable.removeTable("minecraft:chests/abandoned_mineshaft");
mods.ltt.LootTable.removeTable("minecraft:chests/desert_pyramid");
mods.ltt.LootTable.removeTable("minecraft:chests/end_city_treasure");
mods.ltt.LootTable.removeTable("minecraft:chests/igloo_chest");
mods.ltt.LootTable.removeTable("minecraft:chests/jungle_temple");
mods.ltt.LootTable.removeTable("minecraft:chests/jungle_temple_dispenser");
mods.ltt.LootTable.removeTable("minecraft:chests/nether_bridge");
mods.ltt.LootTable.removeTable("minecraft:chests/spawn_bonus_chest");
mods.ltt.LootTable.removeTable("minecraft:chests/stronghold_corridor");
mods.ltt.LootTable.removeTable("minecraft:chests/stronghold_crossing");
mods.ltt.LootTable.removeTable("minecraft:chests/stronghold_library");
mods.ltt.LootTable.removeTable("minecraft:chests/village_blacksmith");
mods.ltt.LootTable.removeTable("minecraft:chests/woodland_mansion");
mods.ltt.LootTable.removeTable("minecraft:entities/wither_skeleton");
mods.ltt.LootTable.removeTable("forestry:chests/village_naturalist");
mods.ltt.LootTable.removeTable("immersiveengineering:chests/engineers_house");
mods.ltt.LootTable.removeTable("immersiveengineering:chests/stronghold_library");
mods.ltt.LootTable.removeTable("immersiveengineering:chests/village_blacksmith");
mods.ltt.LootTable.removeTable("railcraft:chests/village_workshop");
mods.ltt.LootTable.removeTable("minecraft:chests/simple_dungeon");

val simple_dungeon = LootTables.getTable("minecraft:chests/simple_dungeon");
simple_dungeon.clear();
val supercar = simple_dungeon.addPool("supercar", 1, 3, 0, 0);
val supercarhr = simple_dungeon.addPool("supercarhr", 1, 1, 0, 0);
val supercarfood = simple_dungeon.addPool("supercarfood", 1, 5, 0, 0);
val supercarsseed = simple_dungeon.addPool("supercarsseed", 1, 4, 0, 0);
val supercarstresure = simple_dungeon.addPool("supercarstresure", 1, 2, 0, 0);

supercar.addItemEntry(<minecraft:torch>, 1);
supercar.addItemEntry(<minecraft:potion>.withTag({Potion: "minecraft:water"}), 1);
supercar.addItemEntry(<minecraft:apple>, 1);
supercar.addItemEntry(<minecraft:beetroot_seeds>, 1);
supercar.addItemEntry(<minecraft:bone>, 1);
supercar.addItemEntry(<immersiveengineering:seed>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_constantan>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_bronze>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_copper>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_nickel>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_aluminum>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_lead>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_steel>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_platinum>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_electrum>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_invar>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_silver>, 1);
supercarhr.addItemEntry(<thermalfoundation:horse_armor_tin>, 1);
supercarhr.addItemEntry(<minecraft:diamond_horse_armor>, 1);
supercarhr.addItemEntry(<minecraft:golden_horse_armor>, 1);
supercarhr.addItemEntry(<minecraft:iron_horse_armor>, 1);
supercar.addItemEntry(<minecraft:skull:1>, 1);
supercar.addItemEntry(<minecraft:dye>, 1);
supercar.addItemEntry(<minecraft:dye:1>, 1);
supercar.addItemEntry(<minecraft:dye:3>, 1);
supercar.addItemEntry(<minecraft:dye:2>, 1);
supercar.addItemEntry(<minecraft:dye:4>, 1);
supercar.addItemEntry(<minecraft:dye:5>, 1);
supercar.addItemEntry(<minecraft:dye:6>, 1);
supercar.addItemEntry(<minecraft:dye:7>, 1);
supercar.addItemEntry(<minecraft:slime_ball>, 1);
supercar.addItemEntry(<minecraft:dye:15>, 1);
supercar.addItemEntry(<minecraft:dye:13>, 1);
supercar.addItemEntry(<minecraft:dye:14>, 1);
supercar.addItemEntry(<minecraft:dye:8>, 1);
supercar.addItemEntry(<minecraft:dye:9>, 1);
supercar.addItemEntry(<minecraft:dye:10>, 1);
supercar.addItemEntry(<minecraft:dye:11>, 1);
supercar.addItemEntry(<minecraft:dye:12>, 1);
supercar.addItemEntry(<minecraft:arrow>, 1);
supercar.addItemEntry(<minecraft:skull>, 1);
supercar.addItemEntry(<bionisation3:guardianbrain>, 1);
supercarfood.addItemEntry(<minecraft:cake>, 1);
supercarfood.addItemEntry(<minecraft:cooked_porkchop>, 1);
supercarfood.addItemEntry(<minecraft:cooked_chicken>, 1);
supercarfood.addItemEntry(<minecraft:apple>, 1);
supercarfood.addItemEntry(<minecraft:bread>, 1);
supercarfood.addItemEntry(<minecraft:potion>.withTag({Potion: "minecraft:water"}), 1);
supercarsseed.addItemEntry(<minecraft:beetroot_seeds>, 1);
supercarsseed.addItemEntry(<bionisation3:dillseed>, 1);
supercarsseed.addItemEntry(<minecraft:melon_seeds>, 1);
supercarsseed.addItemEntry(<minecraft:pumpkin_seeds>, 1);
supercarsseed.addItemEntry(<minecraft:wheat_seeds>, 1);
supercarsseed.addItemEntry(<bionisation3:yarrowseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:appleseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:oakseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:birchseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:spruceseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:darkoakseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:jungleseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:acaciaseed>, 1);
supercarsseed.addItemEntry(<dynamictrees:cactusseed>, 1);
supercarstresure.addItemEntry(<minecraft:name_tag>, 1);
supercarstresure.addItemEntry(<minecraft:saddle>, 1);
supercarstresure.addItemEntry(<minecraft:bone>, 3);
supercarstresure.addItemEntry(<minecraft:totem_of_undying>, 1);
supercarstresure.addItemEntry(<minecraft:ender_pearl>, 5);
supercarstresure.addItemEntry(<minecraft:prismarine_crystals>, 3);
supercarstresure.addItemEntry(<minecraft:prismarine_shard>, 3);
supercarstresure.addItemEntry(<progressiontweaks:tomahawk>, 2);
supercarstresure.addItemEntry(<progressiontweaks:spear>, 4);
supercarstresure.addItemEntry(<minecraft:gunpowder>, 3);
supercarstresure.addItemEntry(<minecraft:string>, 5);
supercarstresure.addItemEntry(<draconicevolution:draconium_dust>, 5);
supercarstresure.addItemEntry(<minecraft:rotten_flesh>, 5);
supercarstresure.addItemEntry(<minecraft:golden_apple>, 1);
supercarstresure.addItemEntry(<minecraft:golden_apple:1>, 1);
supercarstresure.addItemEntry(<minecraft:golden_carrot>, 1);

furnace.removeAll();
recipes.removeAll();
mods.avaritia.ExtremeCrafting.remove(<avaritia:skullfire_sword>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:ultimate_stew>);

mods.alchemistry.Combiner.removeAllRecipes();

mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:52>, [<alchemistry:element:6> * 40, <alchemistry:element:1> * 56]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:53>, [<alchemistry:element:6> * 2, <alchemistry:element:1> * 3, <alchemistry:element:17>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:51>, [<alchemistry:element:56>, <alchemistry:element:16>, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:50>, [<alchemistry:element:33> * 4, <alchemistry:element:16> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:49>, [<alchemistry:element:56>, <alchemistry:element:29>, <alchemistry:element:14> * 2, <alchemistry:element:8> * 6]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:48>, [<alchemistry:element:22> * 2, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:60>, [<alchemistry:element:80>, <alchemistry:element:16>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:45>, [<alchemistry:element:48>, <alchemistry:element:16>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:46>, [<alchemistry:element:24> * 2, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:47>, [<alchemistry:element:51> * 2, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:59>, [<alchemistry:element:6> * 8, <alchemistry:element:1> * 10, <alchemistry:element:7> * 4, <alchemistry:element:8> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:58>, [<alchemistry:element:6> * 16, <alchemistry:element:1> * 18, <alchemistry:element:7> * 2, <alchemistry:element:8> * 5, <alchemistry:element:16>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:57>, [<alchemistry:element:6> * 9, <alchemistry:element:1> * 8, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:56>, [<alchemistry:element:6> * 17, <alchemistry:element:1> * 21, <alchemistry:element:7>, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:54>, [<alchemistry:element:19>, <alchemistry:element:6>, <alchemistry:element:7>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:55>, [<alchemistry:element:6> * 9, <alchemistry:element:1> * 13, <alchemistry:element:7>, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:44>, [<alchemistry:element:29>, <alchemistry:element:17> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:43>, [<alchemistry:element:12>, <alchemistry:element:16>, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:42>, [<alchemistry:element:19>, <alchemistry:element:25>, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:41>, [<alchemistry:element:28>, <alchemistry:element:17> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:40>, [<alchemistry:element:19> * 4, <alchemistry:element:24> * 2, <alchemistry:element:8> * 7]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:39>, [<alchemistry:element:6> * 6, <alchemistry:element:1> * 14]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:38>, [<alchemistry:element:6> * 5, <alchemistry:element:1> * 12]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:37>, [<alchemistry:element:6> * 4, <alchemistry:element:1> * 10]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:36>, [<alchemistry:element:6> * 3, <alchemistry:element:1> * 8]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:17>, [<alchemistry:element:38>, <alchemistry:compound:12>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:16>, [<alchemistry:element:20> * 5, <alchemistry:compound:14> * 6, <alchemistry:compound:15> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:15>, [<alchemistry:element:8>, <alchemistry:element:1>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:14>, [<alchemistry:element:15>, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:13>, [<alchemistry:element:20>, <alchemistry:compound:12>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:12>, [<alchemistry:element:6>, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:11>, [<alchemistry:element:6> * 12, <alchemistry:element:1> * 22, <alchemistry:element:8> * 11]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:10>, [<alchemistry:element:26> * 2, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:9>, [<alchemistry:element:6> * 3, <alchemistry:element:1> * 7, <alchemistry:element:7>, <alchemistry:element:8> * 2, <alchemistry:element:16>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound>, [<alchemistry:element:6> * 6, <alchemistry:element:1> * 10, <alchemistry:element:8> * 5]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:1>, [<alchemistry:element:14>, <alchemistry:element:8> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:2>, [<alchemistry:element:19>, <alchemistry:element:7>, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:3>, [<alchemistry:element:13> * 2, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:4>, [<alchemistry:element:12>, <alchemistry:element:8>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:6>, [<alchemistry:element:11>, <alchemistry:element:17>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:5>, [<alchemistry:element:19>, <alchemistry:element:17>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:7>, [<alchemistry:element:1> * 2, <alchemistry:element:8>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:8>, [<alchemistry:compound:3>, <alchemistry:compound:1> * 2, <alchemistry:compound:7> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:35>, [<alchemistry:element:6> * 2, <alchemistry:element:1> * 6]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:34>, [<alchemistry:element:6>, <alchemistry:element:1> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:33>, [<alchemistry:compound:3> * 2, <alchemistry:compound:1>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:32>, [<alchemistry:element:6> * 11, <alchemistry:element:1> * 17, <alchemistry:element:7>, <alchemistry:element:8> * 3]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:31>, [<alchemistry:element:19> * 2, <alchemistry:compound:12>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:30>, [<alchemistry:compound:29> * 2, <alchemistry:element:1>, <alchemistry:compound:14>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:29>, [<alchemistry:element:7>, <alchemistry:element:1> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:28>, [<alchemistry:element:6>, <alchemistry:element:8>, <alchemistry:compound:27> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:27>, [<alchemistry:element:7>, <alchemistry:element:1> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:26>, [<alchemistry:element:6> * 2, <alchemistry:element:1> * 5, <alchemistry:compound:15>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:25>, [<alchemistry:element:82>, <alchemistry:element:53> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:24>, [<alchemistry:element:6> * 18, <alchemistry:element:1> * 32, <alchemistry:element:8> * 2]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:23>, [<alchemistry:element:27>, <alchemistry:element:13> * 2, <alchemistry:element:8> * 4]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:22>, [<alchemistry:element:30>, <alchemistry:element:8>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:21>, [<alchemistry:element:6> * 12, <alchemistry:element:1> * 17, <alchemistry:element:7> * 2, <alchemistry:element:8> * 4, <alchemistry:element:15>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:20>, [<alchemistry:element:6> * 32, <alchemistry:element:1> * 44, <alchemistry:element:8> * 8]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:19>, [<alchemistry:element:6> * 12, <alchemistry:element:1> * 20, <alchemistry:element:8> * 10]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:compound:18>, [<alchemistry:element:4> * 3, <alchemistry:element:13> * 2, <alchemistry:element:14> * 6, <alchemistry:element:8> * 18]);

mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:4>, [<alchemistry:element:4> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:11>, [<alchemistry:element:11> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:13>, [<alchemistry:element:13> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:12>, [<alchemistry:element:12> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:14>, [<alchemistry:element:14> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:19>, [<alchemistry:element:19> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:20>, [<alchemistry:element:20> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:41>, [<alchemistry:element:41> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:31>, [<alchemistry:element:31> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:76>, [<alchemistry:element:76> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:32>, [<alchemistry:element:32> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:33>, [<alchemistry:element:33> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:34>, [<alchemistry:element:34> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:37>, [<alchemistry:element:37> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:40>, [<alchemistry:element:40> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:38>, [<alchemistry:element:38> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:39>, [<alchemistry:element:39> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:75>, [<alchemistry:element:75> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:74>, [<alchemistry:element:74> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:73>, [<alchemistry:element:73> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:88>, [<alchemistry:element:88> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:89>, [<alchemistry:element:89> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:91>, [<alchemistry:element:91> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:92>, [<alchemistry:element:92> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:83>, [<alchemistry:element:83> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:69>, [<alchemistry:element:69> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:5>, [<alchemistry:element:5> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:30>, [<alchemistry:element:30> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:29>, [<alchemistry:element:29> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:28>, [<alchemistry:element:28> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:27>, [<alchemistry:element:27> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:25>, [<alchemistry:element:25> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:24>, [<alchemistry:element:24> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:23>, [<alchemistry:element:23> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:22>, [<alchemistry:element:22> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:21>, [<alchemistry:element:21> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:55>, [<alchemistry:element:55> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:52>, [<alchemistry:element:52> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:51>, [<alchemistry:element:51> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:61>, [<alchemistry:element:61> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:62>, [<alchemistry:element:62> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:63>, [<alchemistry:element:63> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:64>, [<alchemistry:element:64> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:65>, [<alchemistry:element:65> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:105>, [<alchemistry:element:105> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:104>, [<alchemistry:element:104> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:102>, [<alchemistry:element:102> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:103>, [<alchemistry:element:103> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:101>, [<alchemistry:element:101> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:100>, [<alchemistry:element:100> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:78>, [<alchemistry:element:78> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:77>, [<alchemistry:element:77> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:66>, [<alchemistry:element:66> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:107>, [<alchemistry:element:107> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:106>, [<alchemistry:element:106> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:108>, [<alchemistry:element:108> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:109>, [<alchemistry:element:109> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:110>, [<alchemistry:element:110> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:111>, [<alchemistry:element:111> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:112>, [<alchemistry:element:112> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:114>, [<alchemistry:element:114> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:113>, [<alchemistry:element:113> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:44>, [<alchemistry:element:44> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:42>, [<alchemistry:element:42> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:43>, [<alchemistry:element:43> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:45>, [<alchemistry:element:45> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:46>, [<alchemistry:element:46> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:47>, [<alchemistry:element:47> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:48>, [<alchemistry:element:48> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:49>, [<alchemistry:element:49> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:50>, [<alchemistry:element:50> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:3>, [<alchemistry:element:3> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:56>, [<alchemistry:element:56> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:70>, [<alchemistry:element:70> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:84>, [<alchemistry:element:84> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:97>, [<alchemistry:element:97> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:96>, [<alchemistry:element:96> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:72>, [<alchemistry:element:72> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:60>, [<alchemistry:element:60> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:59>, [<alchemistry:element:59> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:58>, [<alchemistry:element:58> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:57>, [<alchemistry:element:57> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:71>, [<alchemistry:element:71> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:85>, [<alchemistry:element:85> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:98>, [<alchemistry:element:98> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:99>, [<alchemistry:element:99> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:87>, [<alchemistry:element:87> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:90>, [<alchemistry:element:90> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:93>, [<alchemistry:element:93> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:94>, [<alchemistry:element:94> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:67>, [<alchemistry:element:67> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:81>, [<alchemistry:element:81> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:82>, [<alchemistry:element:82> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:95>, [<alchemistry:element:95> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:68>, [<alchemistry:element:68> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:115>, [<alchemistry:element:115> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:116>, [<alchemistry:element:116> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:117>, [<alchemistry:element:117> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<alchemistry:ingot:118>, [<alchemistry:element:118> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<minecraft:iron_ingot>, [<alchemistry:element:26> * 16, <advancedrocketry:crystal:*>]);
mods.alchemistry.Combiner.addRecipe(<minecraft:gold_ingot>, [<alchemistry:element:79> * 16, <advancedrocketry:crystal:*>]);