#Name: 2RC12draconic.zs
#Author: Austinsupercar

print("Initializing '2RC12draconic'...");

//fluid programer

val coderatomicafinf = mods.modularmachinery.RecipeBuilder.newBuilder("coderatomicafinf", "coder", 100, 1);
coderatomicafinf.addEnergyPerTickInput(100000);
coderatomicafinf.addFluidOutput(<liquid:yinfinity> * 10);
coderatomicafinf.addFluidInput(<liquid:neutron> * 32000);
coderatomicafinf.addFluidInput(<liquid:yliquidmosneutronium> * 32000);
coderatomicafinf.addItemInput(<contenttweaker:sign_c> * 64);
coderatomicafinf.addItemInput(<avaritia:cosmic_meatballs> * 64);
coderatomicafinf.addItemInput(<avaritia:ultimate_stew> * 64);
coderatomicafinf.addItemInput(<extendedcrafting:material:32> * 64);
coderatomicafinf.addItemInput(<extendedcrafting:singularity_ultimate> * 16);
coderatomicafinf.build();

//Crafting

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:ultimate_stew>, [
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <draconicevolution:chaos_shard>, <draconicevolution:chaotic_core>, <draconicevolution:chaos_shard>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <draconicevolution:chaotic_core>, <draconicevolution:chaos_shard>, <draconicevolution:chaotic_core>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:cosmic_meatballs>, [
	[<contenttweaker:broken_down_organic_matter>, <contenttweaker:broken_down_organic_matter>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:partly_digested_matter_suivyxium_infused>, <contenttweaker:partly_digested_matter_suivyxium_infused>], 
	[<contenttweaker:broken_down_organic_matter>, <contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <contenttweaker:sign_c>, <contenttweaker:partly_digested_matter_suivyxium_infused>], 
	[<contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <contenttweaker:sign_c>], 
	[<contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <contenttweaker:sign_c>], 
	[<contenttweaker:partly_digested_matter_silicon_infused>, <contenttweaker:sign_c>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <extendedcrafting:material:32>, <contenttweaker:sign_c>, <contenttweaker:partly_digested_matter_herobrine_infused>], 
	[<contenttweaker:partly_digested_matter_silicon_infused>, <contenttweaker:partly_digested_matter_silicon_infused>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:partly_digested_matter_herobrine_infused>, <contenttweaker:partly_digested_matter_herobrine_infused>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:7>, [
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[<ore:record>, <ore:record>, <ore:record>, <ore:record>, <draconicevolution:chaos_shard>, <ore:record>, <ore:record>, <ore:record>, <ore:record>], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null], 
	[null, null, null, null, <ore:record>, null, null, null, null]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:compressed_crafting_table>, [
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>], 
	[<ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>, <ore:craftingTableWood>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:double_compressed_crafting_table>, [
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>], 
	[<avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>, <avaritia:compressed_crafting_table>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <contenttweaker:super_flint>, [
	[<avaritia:singularity:3>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <avaritia:singularity:2>], 
	[<draconicevolution:draconic_ingot>, <avaritia:singularity:4>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:singularity:1>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:cosmic_meatballs>, <avaritia:singularity:5>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:singularity>, <avaritia:cosmic_meatballs>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>, <avaritia:singularity:14>, <avaritia:singularity:12>, <avaritia:singularity:14>, <contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>, <avaritia:singularity:12>, <draconicevolution:chaotic_core>, <avaritia:singularity:12>, <contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:cosmic_meatballs>, <contenttweaker:sign_c>, <avaritia:singularity:13>, <avaritia:singularity:12>, <avaritia:singularity:13>, <contenttweaker:sign_c>, <avaritia:cosmic_meatballs>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:cosmic_meatballs>, <avaritia:singularity:11>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:singularity:6>, <avaritia:cosmic_meatballs>, <draconicevolution:draconic_ingot>], 
	[<draconicevolution:draconic_ingot>, <avaritia:singularity:10>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:ultimate_stew>, <avaritia:singularity:7>, <draconicevolution:draconic_ingot>], 
	[<avaritia:singularity:9>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <avaritia:singularity:8>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:6>, [
	[<draconicevolution:chaos_shard>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <draconicevolution:chaos_shard>], 
	[<avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:resource:7>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:ultimate_stew>, <avaritia:resource:5>, <avaritia:singularity:12>, <contenttweaker:gem_c>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:ultimate_stew>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:ultimate_stew>, <avaritia:resource:7>, <contenttweaker:gem_c>, <avaritia:singularity:12>, <contenttweaker:gem_c>, <avaritia:resource:7>, <avaritia:ultimate_stew>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:ultimate_stew>, <avaritia:resource:5>, <avaritia:singularity:12>, <contenttweaker:gem_c>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:ultimate_stew>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:resource:7>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:resource:5>], 
	[<avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:cosmic_meatballs>, <avaritia:resource:5>, <avaritia:singularity:12>, <avaritia:resource:5>], 
	[<draconicevolution:chaos_shard>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <avaritia:resource:5>, <draconicevolution:chaos_shard>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:extreme_crafting_table>, [
	[<avaritia:resource:1>, <avaritia:resource:1>, <avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>, <avaritia:resource:1>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <draconicevolution:chaotic_core>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>, <avaritia:resource:1>], 
	[<avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>, <avaritia:resource:1>]
]);

mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:neutronium_compressor>, [
	[null, null, null, null, <draconicevolution:chaos_shard>, null, null, null, null], 
	[null, null, null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null, null, null], 
	[null, null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <avaritia:resource:1>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null, null], 
	[null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <avaritia:resource:1>, <draconicevolution:chaotic_core>, <avaritia:resource:1>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null], 
	[<draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <avaritia:resource:1>, <draconicevolution:chaotic_core>, <extendedcrafting:compressor>, <draconicevolution:chaotic_core>, <avaritia:resource:1>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>], 
	[null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <avaritia:resource:1>, <draconicevolution:chaotic_core>, <avaritia:resource:1>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null], 
	[null, null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <avaritia:resource:1>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null, null], 
	[null, null, null, <draconicevolution:chaos_shard>, <contenttweaker:sign_c>, <draconicevolution:chaos_shard>, null, null, null], 
	[null, null, null, null, <draconicevolution:chaos_shard>, null, null, null, null]
]);

//Carpenter

mods.forestry.Carpenter.addRecipe(<draconicevolution:crafting_injector>, [[<minecraft:diamond>, <draconicevolution:draconic_core>, <minecraft:diamond>], [<ore:cobblestone>, <avaritia:block_resource>, <ore:cobblestone>], [<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconic_core>, [[<draconicevolution:draconium_ingot>, <ore:ingotGold>, <draconicevolution:draconium_ingot>], [<ore:ingotGold>, <contenttweaker:sign_c>, <ore:ingotGold>], [<draconicevolution:draconium_ingot>, <ore:ingotGold>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:wyvern_core>, [[<draconicevolution:draconium_ingot>, <draconicevolution:draconic_core>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconic_core>, <contenttweaker:sign_c>, <draconicevolution:draconic_core>], [<draconicevolution:draconium_ingot>, <draconicevolution:draconic_core>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:3>, [[<draconicevolution:energy_crystal:6>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:4>, [[<draconicevolution:energy_crystal:7>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:5>, [[<draconicevolution:energy_crystal:8>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:chorus_plant>, [[<minecraft:end_stone>, <ore:treeLeaves>, <minecraft:end_stone>], [<ore:treeLeaves>, <minecraft:end_stone>, <ore:treeLeaves>], [<minecraft:end_stone>, <ore:treeLeaves>, <minecraft:end_stone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:chorus_flower>, [[<minecraft:end_stone>, <minecraft:chorus_plant>, <minecraft:end_stone>], [<minecraft:chorus_plant>, <minecraft:end_stone>, <minecraft:chorus_plant>], [<minecraft:end_stone>, <minecraft:chorus_plant>, <minecraft:end_stone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:end_rod>, [[<minecraft:blaze_rod>], [<minecraft:chorus_fruit_popped>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:shulker_shell>, [[<minecraft:chorus_fruit_popped>, <minecraft:chorus_fruit_popped>, <minecraft:chorus_fruit_popped>], [<minecraft:chorus_fruit_popped>, <contenttweaker:sign_c>, <minecraft:chorus_fruit_popped>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:chorus_fruit_popped>, [[<minecraft:chorus_fruit>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:end_crystal>, [[<ore:paneGlass>, <ore:paneGlass>, <ore:paneGlass>], [<ore:paneGlass>, <draconicevolution:wyvern_core>, <ore:paneGlass>], [<ore:paneGlass>, <minecraft:ghast_tear>, <ore:paneGlass>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<minecraft:ender_chest>, [[<ore:obsidian>, <ore:obsidian>, <ore:obsidian>], [<ore:obsidian>, <contenttweaker:mos_neutronium_compound_ingot>, <ore:obsidian>], [<ore:obsidian>, <ore:obsidian>, <ore:obsidian>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_ore>, [[<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>], [<contenttweaker:mos_neutronium_compound_ingot>, <ore:oreMithril>, <contenttweaker:mos_neutronium_compound_ingot>], [<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<contenttweaker:gem_c>, [[<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>], [<avaritia:endest_pearl>, <contenttweaker:gem_e>, <avaritia:endest_pearl>], [<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_block:1>, [[<contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>], [<contenttweaker:sign_c>, <draconicevolution:draconium_block>, <contenttweaker:sign_c>], [<contenttweaker:sign_c>, <contenttweaker:sign_c>, <contenttweaker:sign_c>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:infused_obsidian>, [[<minecraft:blaze_powder>, <ore:obsidian>, <minecraft:blaze_powder>], [<ore:obsidian>, <draconicevolution:draconium_dust>, <ore:obsidian>], [<minecraft:blaze_powder>, <ore:obsidian>, <minecraft:blaze_powder>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:dislocator_receptacle>, [[<minecraft:iron_ingot>, <draconicevolution:draconic_core>, <minecraft:iron_ingot>], [null, <draconicevolution:infused_obsidian>, null], [<minecraft:iron_ingot>, null, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:item_dislocation_inhibitor>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_bars>, <draconicevolution:magnet>, <minecraft:iron_bars>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:generator>, [[<minecraft:netherbrick>, <minecraft:iron_ingot>, <minecraft:netherbrick>], [<minecraft:iron_ingot>, <minecraft:furnace>, <minecraft:iron_ingot>], [<minecraft:netherbrick>, <draconicevolution:draconic_core>, <minecraft:netherbrick>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:grinder>, [[<minecraft:iron_ingot>, <draconicevolution:draconium_ingot>, <minecraft:iron_ingot>], [<minecraft:diamond_sword>, <draconicevolution:draconic_core>, <minecraft:diamond_sword>], [<minecraft:iron_ingot>, <minecraft:furnace>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:particle_generator>, [[<minecraft:redstone_block>, <minecraft:blaze_rod>, <minecraft:redstone_block>], [<minecraft:blaze_rod>, <draconicevolution:draconic_core>, <minecraft:blaze_rod>], [<minecraft:redstone_block>, <minecraft:blaze_rod>, <minecraft:redstone_block>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:particle_generator:2>, [[<minecraft:diamond>, null, <minecraft:diamond>], [null, <draconicevolution:particle_generator>, null], [<minecraft:diamond>, null, <minecraft:diamond>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_infuser>, [[<draconicevolution:draconium_ingot>, <draconicevolution:particle_generator:2>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconic_core>, <alchemistry:chemical_combiner>, <draconicevolution:draconic_core>], [<draconicevolution:draconium_ingot>, <draconicevolution:draconic_core>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:dislocator_pedestal>, [[null, <minecraft:stone_pressure_plate>, null], [null, <ore:stone>, null], [<ore:slabStone>, <minecraft:blaze_powder>, <ore:slabStone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:rain_sensor>, [[null, <minecraft:bucket>, null], [<minecraft:redstone>, <minecraft:stone_pressure_plate>, <minecraft:redstone>], [<ore:slabStone>, <ore:slabStone>, <ore:slabStone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:potentiometer>, [[null, <ore:plankWood>, null], [<minecraft:redstone>, <draconicevolution:draconium_dust>, <minecraft:redstone>], [<ore:slabStone>, <ore:slabStone>, <ore:slabStone>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:entity_detector>, [[<ore:gemLapis>, <minecraft:ender_eye>, <ore:gemLapis>], [<minecraft:redstone>, <draconicevolution:draconium_ingot>, <minecraft:redstone>], [<minecraft:iron_ingot>, <draconicevolution:draconic_core>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:entity_detector:1>, [[<ore:blockRedstone>, <minecraft:skull:1>, <ore:blockRedstone>], [<ore:blockLapis>, <minecraft:diamond>, <ore:blockLapis>], [<draconicevolution:draconium_ingot>, <draconicevolution:entity_detector>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:diss_enchanter>, [[<minecraft:emerald>, <draconicevolution:draconic_core>, <minecraft:emerald>], [<minecraft:book>, <minecraft:enchanting_table>, <minecraft:book>], [<ore:bookshelf>, <ore:bookshelf>, <ore:bookshelf>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_storage_core>, [[<draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>], [<draconicevolution:wyvern_energy_core>, <draconicevolution:wyvern_core>, <draconicevolution:wyvern_energy_core>], [<draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_pylon>, [[<draconicevolution:draconium_ingot>, <minecraft:ender_eye>, <draconicevolution:draconium_ingot>], [<minecraft:emerald>, <draconicevolution:draconic_core>, <minecraft:emerald>], [<draconicevolution:draconium_ingot>, <minecraft:diamond>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:fusion_crafting_core>, [[<ore:blockLapis>, <minecraft:diamond>, <ore:blockLapis>], [<minecraft:diamond>, <draconicevolution:draconic_core>, <minecraft:diamond>], [<ore:blockLapis>, <minecraft:diamond>, <ore:blockLapis>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:1>, [[<draconicevolution:wyvern_energy_core>, <draconicevolution:energy_crystal>, <draconicevolution:wyvern_energy_core>], [<draconicevolution:energy_crystal>, <draconicevolution:draconic_core>, <draconicevolution:energy_crystal>], [<draconicevolution:wyvern_energy_core>, <draconicevolution:energy_crystal>, <draconicevolution:wyvern_energy_core>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal>, [[null, <minecraft:diamond>, null], [<minecraft:diamond>, <draconicevolution:wyvern_energy_core>, <minecraft:diamond>], [null, <minecraft:diamond>, null]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:celestial_manipulator>, [[<ore:blockRedstone>, <minecraft:clock>, <ore:blockRedstone>], [<draconicevolution:draconium_ingot>, <minecraft:dragon_egg>, <draconicevolution:draconium_ingot>], [<minecraft:iron_ingot>, <draconicevolution:wyvern_core>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:6>, [[<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>], [<minecraft:ender_eye>, <draconicevolution:energy_crystal>, <minecraft:ender_eye>], [<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:7>, [[<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>], [<minecraft:ender_eye>, <draconicevolution:energy_crystal:1>, <minecraft:ender_eye>], [<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:energy_crystal:8>, [[<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>], [<minecraft:ender_eye>, <draconicevolution:energy_crystal:2>, <minecraft:ender_eye>], [<minecraft:ender_pearl>, <draconicevolution:particle_generator>, <minecraft:ender_pearl>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:flow_gate>, [[<minecraft:iron_ingot>, <draconicevolution:potentiometer>, <minecraft:iron_ingot>], [<ore:blockRedstone>, <draconicevolution:draconic_core>, <ore:blockRedstone>], [<minecraft:iron_ingot>, <minecraft:comparator>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:flow_gate:8>, [[<minecraft:iron_ingot>, <draconicevolution:potentiometer>, <minecraft:iron_ingot>], [<minecraft:bucket>, <draconicevolution:draconic_core>, <minecraft:bucket>], [<minecraft:iron_ingot>, <minecraft:comparator>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:reactor_part>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<draconicevolution:wyvern_core>, <draconicevolution:draconic_ingot>, null], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:chaos_shard>, [[<draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>], [<draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>], [<draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>, <draconicevolution:chaos_shard:1>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:chaos_shard:1>, [[<draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>], [<draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>], [<draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>, <draconicevolution:chaos_shard:2>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:chaos_shard:2>, [[<draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>], [<draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>], [<draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>, <draconicevolution:chaos_shard:3>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_ingot>, [[<draconicevolution:draconium_dust>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconic_ingot> * 9, [[<draconicevolution:draconic_block>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:dragon_heart>, [[<contenttweaker:sign_c>, <contenttweaker:mos_neutronium_compound_ingot>, <contenttweaker:sign_c>], [<contenttweaker:sign_c>, <draconicevolution:draconic_core>, <contenttweaker:sign_c>], [<ore:ingotSignalum>, <contenttweaker:sign_c>, <ore:ingotSignalum>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_block>, [[<draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconic_block>, [[<draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>], [<draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>], [<draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:reactor_part:4>, [[<ore:ingotGold>, <minecraft:diamond>, <ore:ingotGold>], [<minecraft:diamond>, <draconicevolution:wyvern_core>, <minecraft:diamond>], [<ore:ingotGold>, <minecraft:diamond>, <ore:ingotGold>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:reactor_part:3>, [[null, <draconicevolution:reactor_part:1>, <draconicevolution:reactor_part:2>], [<draconicevolution:wyvern_core>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>], [null, <draconicevolution:reactor_part:1>, <draconicevolution:reactor_part:2>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:reactor_part:2>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [<draconicevolution:draconic_core>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:reactor_part:1>, [[<draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_ingot>], [<draconicevolution:draconic_core>, <draconicevolution:draconium_ingot>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:wyvern_energy_core>, [[<draconicevolution:draconium_ingot>, <ore:blockRedstone>, <draconicevolution:draconium_ingot>], [<ore:blockRedstone>, <draconicevolution:draconic_core>, <ore:blockRedstone>], [<draconicevolution:draconium_ingot>, <ore:blockRedstone>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconic_energy_core>, [[<draconicevolution:draconic_ingot>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconic_ingot>], [<draconicevolution:wyvern_energy_core>, <draconicevolution:wyvern_core>, <draconicevolution:wyvern_energy_core>], [<draconicevolution:draconic_ingot>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconic_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:crystal_binder>, [[null, <draconicevolution:draconium_ingot>, <minecraft:diamond>], [null, <minecraft:blaze_rod>, <draconicevolution:draconium_ingot>], [<draconicevolution:draconic_core>, null, null]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_capacitor>, [[<draconicevolution:draconium_ingot>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconium_ingot>], [<draconicevolution:wyvern_energy_core>, <draconicevolution:wyvern_core>, <draconicevolution:wyvern_energy_core>], [<draconicevolution:draconium_ingot>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconium_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:draconium_capacitor:1>, [[<draconicevolution:draconic_energy_core>, <draconicevolution:awakened_core>, <draconicevolution:draconic_energy_core>], [<draconicevolution:draconic_ingot>, <draconicevolution:draconium_capacitor>, <draconicevolution:draconic_ingot>], [<draconicevolution:draconic_energy_core>, <draconicevolution:draconic_ingot>, <draconicevolution:draconic_energy_core>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:dislocator>, [[<minecraft:blaze_powder>, <draconicevolution:draconium_dust>, <minecraft:blaze_powder>], [<draconicevolution:draconium_dust>, <minecraft:ender_eye>, <draconicevolution:draconium_dust>], [<minecraft:blaze_powder>, <draconicevolution:draconium_dust>, <minecraft:blaze_powder>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:magnet>, [[<minecraft:redstone>, null, <minecraft:redstone>], [<draconicevolution:draconium_ingot>, null, <draconicevolution:draconium_ingot>], [<minecraft:iron_ingot>, <draconicevolution:dislocator>, <minecraft:iron_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<draconicevolution:magnet:1>, [[<draconicevolution:draconium_ingot>, null, <draconicevolution:draconium_ingot>], [<minecraft:redstone>, null, <minecraft:redstone>], [<draconicevolution:draconic_ingot>, <draconicevolution:magnet>, <draconicevolution:draconic_ingot>]], 5, <liquid:yliquidmosneutronium> * 1000);
mods.forestry.Carpenter.addRecipe(<avaritia:resource:5>, [[<contenttweaker:mos_neutronium_compound_ingot>, <contenttweaker:super_flint>, <contenttweaker:mos_neutronium_compound_ingot>], [<contenttweaker:super_flint>, <contenttweaker:sign_c>, <contenttweaker:super_flint>], [<contenttweaker:mos_neutronium_compound_ingot>, <contenttweaker:super_flint>, <contenttweaker:mos_neutronium_compound_ingot>]], 5, <liquid:yinfinity> * 5000);
mods.forestry.Carpenter.addRecipe(<minecraft:end_portal_frame>, [[<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>], [<minecraft:end_stone>, <contenttweaker:sign_c>, <minecraft:end_stone>], [<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>]], 5, <liquid:yliquidmosneutronium> * 1000);

//Compressor

mods.extendedcrafting.CompressionCrafting.addRecipe(<avaritia:singularity:12>, <extendedcrafting:singularity_ultimate>, 1000, <draconicevolution:chaotic_core>, 10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<avaritia:singularity:13>, <extendedcrafting:singularity:33>, 1000, <draconicevolution:chaotic_core>, 10000);
mods.extendedcrafting.CompressionCrafting.addRecipe(<avaritia:singularity:14>, <extendedcrafting:singularity:35>, 1000, <draconicevolution:chaotic_core>, 10000);