#Name: 2RC2stone.zs
#Author: Austinsupercar

print("Initializing '2RC2stone'...");

//Crafting table recipes

recipes.addShaped(<toughasnails:jelled_slime_helmet>, [[<toughasnails:jelled_slime>, <toughasnails:jelled_slime>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<toughasnails:jelled_slime_chestplate>, [[<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:jelled_slime>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:jelled_slime>, <toughasnails:jelled_slime>]]);
recipes.addShaped(<toughasnails:jelled_slime_leggings>, [[<toughasnails:jelled_slime>, <toughasnails:jelled_slime>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>]]);
recipes.addShaped(<toughasnails:jelled_slime_boots>, [[<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>], [<toughasnails:jelled_slime>, <toughasnails:charcoal_filter>, <toughasnails:jelled_slime>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<toughasnails:wool_helmet>, [[<ore:wool>, <ore:wool>, <ore:wool>], [<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<toughasnails:wool_chestplate>, [[<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>], [<ore:wool>, <ore:wool>, <ore:wool>], [<ore:wool>, <ore:wool>, <ore:wool>]]);
recipes.addShaped(<toughasnails:wool_leggings>, [[<ore:wool>, <ore:wool>, <ore:wool>], [<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>], [<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>]]);
recipes.addShaped(<toughasnails:wool_boots>, [[<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>], [<ore:wool>, <toughasnails:charcoal_filter>, <ore:wool>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<toughasnails:fruit_juice>, [[<minecraft:apple>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:1>, [[<minecraft:beetroot>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:2>, [[<minecraft:cactus>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:3>, [[<minecraft:carrot>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:4>, [[<minecraft:chorus_fruit>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:5>, [[<minecraft:speckled_melon>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:6>, [[<minecraft:golden_apple>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:7>, [[<minecraft:golden_carrot>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:8>, [[<minecraft:melon>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:fruit_juice:9>, [[<minecraft:pumpkin>, <minecraft:sugar>, <toughasnails:purified_water_bottle>]]);
recipes.addShaped(<toughasnails:canteen>, [[<toughasnails:charcoal_filter>, <minecraft:leather>, <toughasnails:charcoal_filter>], [<minecraft:leather>, <pyrotech:bucket_wood>, <minecraft:leather>], [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]]);
recipes.addShaped(<toughasnails:ice_cube>, [[<toughasnails:charcoal_filter>, <minecraft:snowball>, <toughasnails:charcoal_filter>], [<minecraft:snowball>, <toughasnails:purified_water_bottle>, <minecraft:snowball>], [<toughasnails:charcoal_filter>, <minecraft:snowball>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<toughasnails:magma_shard>, [[<toughasnails:jelled_slime>, <minecraft:glowstone_dust>, <toughasnails:jelled_slime>], [<minecraft:glowstone_dust>, <toughasnails:jelled_slime>, <minecraft:glowstone_dust>], [<toughasnails:jelled_slime>, <minecraft:glowstone_dust>, <toughasnails:jelled_slime>]]);
recipes.addShaped(<toughasnails:jelled_slime>, [[<ore:slimeball>, <toughasnails:ice_cube>]]);
recipes.addShapeless(<minecraft:wool:1>, [<minecraft:wool>, <ore:dyeOrange>]);
recipes.addShapeless(<minecraft:wool:2>, [<minecraft:wool>, <ore:dyeMagenta>]);
recipes.addShapeless(<minecraft:wool:3>, [<minecraft:wool>, <ore:dyeLightBlue>]);
recipes.addShapeless(<minecraft:wool:4>, [<minecraft:wool>, <ore:dyeYellow>]);
recipes.addShapeless(<minecraft:wool:5>, [<minecraft:wool>, <ore:dyeLime>]);
recipes.addShapeless(<minecraft:wool:6>, [<minecraft:wool>, <ore:dyePink>]);
recipes.addShapeless(<minecraft:wool:7>, [<minecraft:wool>, <ore:dyeGray>]);
recipes.addShapeless(<minecraft:wool:8>, [<minecraft:wool>, <ore:dyeLightGray>]);
recipes.addShapeless(<minecraft:wool:9>, [<minecraft:wool>, <ore:dyeCyan>]);
recipes.addShapeless(<minecraft:wool:10>, [<minecraft:wool>, <ore:dyePurple>]);
recipes.addShapeless(<minecraft:wool:11>, [<minecraft:wool>, <ore:dyeBlue>]);
recipes.addShapeless(<minecraft:wool:12>, [<minecraft:wool>, <ore:dyeBrown>]);
recipes.addShapeless(<minecraft:wool:13>, [<minecraft:wool>, <ore:dyeGreen>]);
recipes.addShapeless(<minecraft:wool:14>, [<minecraft:wool>, <ore:dyeRed>]);
recipes.addShapeless(<minecraft:wool:15>, [<minecraft:wool>, <ore:dyeBlack>]);
recipes.addShaped(<minecraft:leather_helmet>, [[<minecraft:leather>, <minecraft:leather>, <minecraft:leather>], [<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<minecraft:leather_chestplate>, [[<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>], [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>], [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:leather_leggings>, [[<minecraft:leather>, <minecraft:leather>, <minecraft:leather>], [<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>], [<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:leather_boots>, [[<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>], [<minecraft:leather>, <toughasnails:charcoal_filter>, <minecraft:leather>], [<toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>, <toughasnails:charcoal_filter>]]);
recipes.addShaped(<minecraft:wooden_sword>, [[<pyrotech:material:25>, <ore:plankWood>, <pyrotech:material:25>], [<pyrotech:material:25>, <ore:plankWood>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<minecraft:gunpowder>, [[<ore:coal>, <ore:dustSulfur>, <ore:coal>], [<ore:dustSulfur>, <toughasnails:charcoal_filter>, <ore:dustSulfur>], [<ore:coal>, <ore:dustSulfur>, <ore:coal>]]);
recipes.addShaped(<minecraft:diamond_block>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>]]);
recipes.addShaped(<minecraft:coal_block>, [[<minecraft:coal>, <minecraft:coal>, <minecraft:coal>], [<minecraft:coal>, <minecraft:coal>, <minecraft:coal>], [<minecraft:coal>, <minecraft:coal>, <minecraft:coal>]]);
recipes.addShaped(<minecraft:emerald_block>, [[<minecraft:emerald>, <minecraft:emerald>, <minecraft:emerald>], [<minecraft:emerald>, <minecraft:emerald>, <minecraft:emerald>], [<minecraft:emerald>, <minecraft:emerald>, <minecraft:emerald>]]);
recipes.addShaped(<minecraft:book>, [[<minecraft:leather>, <minecraft:paper>, <minecraft:paper>], [<minecraft:leather>, <minecraft:string>, <minecraft:paper>], [<minecraft:leather>, <minecraft:paper>, <minecraft:paper>]]);
recipes.addShaped(<minecraft:writable_book>, [[<minecraft:feather>, <minecraft:book>, <ore:dyeBlack>]]);
recipes.addShaped(<minecraft:cobblestone_wall>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]]);
recipes.addShaped(<pyrotech:thatch>, [[<pyrotech:material:2>, <pyrotech:material:2>, <pyrotech:material:2>], [<pyrotech:material:2>, <pyrotech:material:2>, <pyrotech:material:2>], [<pyrotech:material:2>, <pyrotech:material:2>, <pyrotech:material:2>]]);
recipes.addShaped(<minecraft:hay_block>, [[<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>], [<minecraft:wheat>, <minecraft:wheat>, <minecraft:wheat>]]);
recipes.addShaped(<contenttweaker:tool_stick_a>, [[<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:27>], [<pyrotech:material:25>, <contenttweaker:breaking_stick>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<ore:plankWood>, <minecraft:flint>, <ore:plankWood>], [<pyrotech:material:25>, <ore:plankWood>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:1>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<ore:stone>, <minecraft:flint>, <ore:stone>], [<pyrotech:material:25>, <ore:stone>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:2>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<minecraft:iron_ingot>, <minecraft:flint>, <minecraft:iron_ingot>], [<pyrotech:material:25>, <minecraft:iron_ingot>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:3>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<minecraft:diamond>, <minecraft:flint>, <minecraft:diamond>], [<pyrotech:material:25>, <minecraft:diamond>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:4>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<minecraft:gold_ingot>, <minecraft:flint>, <minecraft:gold_ingot>], [<pyrotech:material:25>, <minecraft:gold_ingot>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:5>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<ore:obsidian>, <minecraft:flint>, <ore:obsidian>], [<pyrotech:material:25>, <ore:obsidian>, <pyrotech:material:25>]]);
recipes.addShaped(<advancedmortars:mortar:6>, [[<pyrotech:material:25>, <pyrotech:material:25>, <contenttweaker:tool_stick_a>], [<minecraft:emerald>, <minecraft:flint>, <minecraft:emerald>], [<pyrotech:material:25>, <minecraft:emerald>, <pyrotech:material:25>]]);
recipes.addShaped(<minecraft:glass_bottle>, [[<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>], [<ore:blockGlass>, <contenttweaker:glue>, <ore:blockGlass>], [<contenttweaker:glue>, <ore:blockGlass>, <contenttweaker:glue>]]);
recipes.addShaped(<geolosys:pro_pick>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_block>], [<contenttweaker:glue>, <contenttweaker:tool_stick_a>, <minecraft:iron_ingot>], [<contenttweaker:glue>, <contenttweaker:tool_stick_a>, <contenttweaker:glue>]]);
recipes.addShaped(<itemfilters:filter>, [[<pyrotech:material:25>, <minecraft:paper>, <pyrotech:material:25>], [<minecraft:paper>, <ore:wool>, <minecraft:paper>], [<pyrotech:material:25>, <minecraft:paper>, <pyrotech:material:25>]]);
recipes.addShaped(<millenaire:wall_mud_brick>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:stone_deco>, <millenaire:stone_deco>, <millenaire:stone_deco>], [<millenaire:stone_deco>, <millenaire:stone_deco>, <millenaire:stone_deco>]]);
recipes.addShaped(<millenaire:stairs_byzantine_tiles>, [[<millenaire:byzantine_tiles>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <contenttweaker:glue>], [<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>]]);
recipes.addShaped(<millenaire:wall_painted_brick_white>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <millenaire:painted_brick_white>], [<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <millenaire:painted_brick_white>]]);
recipes.addShaped(<millenaire:stairs_painted_brick_white>, [[<millenaire:painted_brick_white>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <contenttweaker:glue>], [<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <millenaire:painted_brick_white>]]);
recipes.addShaped(<millenaire:slab_painted_brick_white>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <millenaire:painted_brick_white>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<minecraft:flint_and_steel>, [[<ore:oreIron>, <contenttweaker:tool_stick_a>, <minecraft:brick>], [<contenttweaker:tool_stick_a>, <minecraft:flint>, <pyrotech:material:5>], [<minecraft:brick>, <pyrotech:material:5>, <pyrotech:material:16>]]);
recipes.addShaped(<millenaire:slab_stone_deco:1>, [[<millenaire:painted_brick_white>, <millenaire:painted_brick_white>, <millenaire:painted_brick_white>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:slab_stone_deco>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:stone_deco>, <millenaire:stone_deco>, <millenaire:stone_deco>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:slab_wood_deco:2>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:wood_deco:2>, <millenaire:wood_deco:2>, <millenaire:wood_deco:2>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:slab_wood_deco>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:wood_deco>, <millenaire:wood_deco>, <millenaire:wood_deco>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathdirt_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathdirt>, <millenaire:pathdirt>, <millenaire:pathdirt>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathgravel_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathgravel>, <millenaire:pathgravel>, <millenaire:pathgravel>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathsandstone_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathsandstone>, <millenaire:pathsandstone>, <millenaire:pathsandstone>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathslabs_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathslabs>, <millenaire:pathslabs>, <millenaire:pathslabs>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathgravelslabs_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathgravelslabs>, <millenaire:pathgravelslabs>, <millenaire:pathgravelslabs>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathochretiles_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathochretiles>, <millenaire:pathochretiles>, <millenaire:pathochretiles>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:pathsnow_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:pathsnow>, <millenaire:pathsnow>, <millenaire:pathsnow>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:byzantine_tiles_slab>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:stairs_thatch>, [[<millenaire:wood_deco:2>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:wood_deco:2>, <millenaire:wood_deco:2>, <contenttweaker:glue>], [<millenaire:wood_deco:2>, <millenaire:wood_deco:2>, <millenaire:wood_deco:2>]]);
recipes.addShaped(<millenaire:stairs_timberframe>, [[<millenaire:wood_deco>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:wood_deco>, <millenaire:wood_deco>, <contenttweaker:glue>], [<millenaire:wood_deco>, <millenaire:wood_deco>, <millenaire:wood_deco>]]);
recipes.addShaped(<millenaire:stairs_mudbrick>, [[<millenaire:stone_deco>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:stone_deco>, <millenaire:stone_deco>, <contenttweaker:glue>], [<millenaire:stone_deco>, <millenaire:stone_deco>, <millenaire:stone_deco>]]);
recipes.addShaped(<millenaire:byzantine_stone_tiles>, [[<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>], [<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:byzantine_sandstone_tiles>, [[<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>], [<ore:sandstone>, <ore:sandstone>, <ore:sandstone>], [<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>]]);
recipes.addShaped(<millenaire:byzantine_stone_ornament>, [[<contenttweaker:glue>, <millenaire:byzantine_tiles>, <contenttweaker:glue>], [<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>], [<minecraft:stonebrick>, <minecraft:stonebrick>, <minecraft:stonebrick>]]);
recipes.addShaped(<millenaire:byzantine_sandstone_ornament>, [[<contenttweaker:glue>, <millenaire:byzantine_tiles>, <contenttweaker:glue>], [<millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>, <millenaire:byzantine_tiles>], [<minecraft:sandstone>, <minecraft:sandstone>, <minecraft:sandstone>]]);
recipes.addShaped(<millenaire:alchemistexplosive>, [[<alchemistry:ingot:118>, <ore:ingotPlutonium>, <alchemistry:ingot:118>], [<projecte:matter_block:1>, <projecte:nova_cataclysm>, <projecte:matter_block:1>], [<alchemistry:ingot:118>, <ore:ingotPlutonium>, <alchemistry:ingot:118>]]);
recipes.addShaped(<millenaire:icebrick>, [[<minecraft:ice>, <contenttweaker:glue>, <minecraft:ice>], [<contenttweaker:glue>, <minecraft:ice>, <contenttweaker:glue>], [<minecraft:ice>, <contenttweaker:glue>, <minecraft:ice>]]);
recipes.addShaped(<millenaire:snowbrick>, [[<minecraft:snow>, <contenttweaker:glue>, <minecraft:snow>], [<contenttweaker:glue>, <minecraft:snow>, <contenttweaker:glue>], [<minecraft:snow>, <contenttweaker:glue>, <minecraft:snow>]]);
recipes.addShaped(<millenaire:snowwall>, [[<contenttweaker:glue>, <contenttweaker:glue>, <contenttweaker:glue>], [<millenaire:snowbrick>, <millenaire:snowbrick>, <millenaire:snowbrick>], [<millenaire:snowbrick>, <millenaire:snowbrick>, <millenaire:snowbrick>]]);
recipes.addShaped(<millenaire:paint_bucket_white>, [[<ore:dyeWhite>, <ore:dyeWhite>, <ore:dyeWhite>], [<ore:dyeWhite>, <minecraft:water_bucket>, <ore:dyeWhite>], [<ore:dyeWhite>, <ore:dyeWhite>, <contenttweaker:tool_stick_a>]]);
recipes.addShapeless(<millenaire:paint_bucket_orange>, [<ore:dyeOrange>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_magenta>, [<ore:dyeMagenta>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_light_blue>, [<ore:dyeLightBlue>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_yellow>, [<ore:dyeYellow>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_lime>, [<ore:dyeLime>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_pink>, [<ore:dyePink>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_gray>, [<ore:dyeGray>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_silver>, [<ore:dyeLightGray>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_cyan>, [<ore:dyeCyan>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_purple>, [<ore:dyePurple>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_blue>, [<ore:dyeBlue>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_brown>, [<ore:dyeBrown>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_green>, [<ore:dyeGreen>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_red>, [<ore:dyeRed>, <millenaire:paint_bucket_white>]);
recipes.addShapeless(<millenaire:paint_bucket_black>, [<ore:dyeBlack>, <millenaire:paint_bucket_white>]);
recipes.addShaped(<pyrotech:material:9>, [[<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>], [<pyrotech:material:4>, <pyrotech:material:24>, <pyrotech:material:4>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:material:24>, [[<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>], [<minecraft:clay_ball>, <contenttweaker:tool_stick_a>, <minecraft:clay_ball>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<progressiontweaks:spear>, [[<pyrotech:material:25>, <pyrotech:material:25>, <minecraft:flint>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<progressiontweaks:tomahawk>, [[<pyrotech:material:25>, <minecraft:flint>, <minecraft:flint>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <minecraft:flint>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_stone>, [[<pyrotech:material:25>, <pyrotech:material:16>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:16>, <pyrotech:material:16>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_flint>, [[<pyrotech:material:25>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:10>, <pyrotech:material:10>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_bone>, [[<pyrotech:material:25>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:11>, <pyrotech:material:11>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_iron>, [[<pyrotech:material:25>, <pyrotech:material:19>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:19>, <pyrotech:material:19>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_gold>, [[<pyrotech:material:25>, <pyrotech:material:34>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:34>, <pyrotech:material:34>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_diamond>, [[<pyrotech:material:25>, <pyrotech:material:18>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:18>, <pyrotech:material:18>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:tongs_obsidian>, [[<pyrotech:material:25>, <pyrotech:material:33>, <pyrotech:material:25>], [<pyrotech:material:27>, <pyrotech:material:33>, <pyrotech:material:33>], [<toughasnails:charcoal_filter>, <pyrotech:material:27>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:log_pile>, [[<ore:logWood>, <ore:logWood>, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>]]);
recipes.addShaped(<pyrotech:refractory_door>, [[<pyrotech:material:5>, <pyrotech:material:5>, <contenttweaker:glue>], [<pyrotech:material:5>, <pyrotech:material:5>, <contenttweaker:glue>], [<pyrotech:material:5>, <pyrotech:material:5>, <contenttweaker:glue>]]);
recipes.addShaped(<pyrotech:stone_door>, [[<pyrotech:material:16>, <pyrotech:material:16>, <contenttweaker:glue>], [<pyrotech:material:16>, <pyrotech:material:16>, <contenttweaker:glue>], [<pyrotech:material:16>, <pyrotech:material:16>, <contenttweaker:glue>]]);
recipes.addShaped(<pyrotech:stone_bricks>, [[<pyrotech:material:16>, <pyrotech:material:25>, <pyrotech:material:16>], [<pyrotech:material:25>, <pyrotech:material:16>, <pyrotech:material:25>], [<pyrotech:material:16>, <pyrotech:material:25>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:refractory_brick_block>, [[<pyrotech:material:5>, <pyrotech:material:25>, <pyrotech:material:5>], [<pyrotech:material:25>, <pyrotech:material:5>, <pyrotech:material:25>], [<pyrotech:material:5>, <pyrotech:material:25>, <pyrotech:material:5>]]);
recipes.addShaped(<pyrotech:cobblestone>, [[<pyrotech:rock:3>, <pyrotech:rock:3>, <pyrotech:rock:3>], [<pyrotech:rock:3>, <pyrotech:rock:3>, <pyrotech:rock:3>], [<pyrotech:rock:3>, <pyrotech:rock:3>, <pyrotech:rock:3>]]);
recipes.addShaped(<pyrotech:cobblestone:1>, [[<pyrotech:rock:2>, <pyrotech:rock:2>, <pyrotech:rock:2>], [<pyrotech:rock:2>, <pyrotech:rock:2>, <pyrotech:rock:2>], [<pyrotech:rock:2>, <pyrotech:rock:2>, <pyrotech:rock:2>]]);
recipes.addShaped(<pyrotech:cobblestone:2>, [[<pyrotech:rock:1>, <pyrotech:rock:1>, <pyrotech:rock:1>], [<pyrotech:rock:1>, <pyrotech:rock:1>, <pyrotech:rock:1>], [<pyrotech:rock:1>, <pyrotech:rock:1>, <pyrotech:rock:1>]]);
recipes.addShaped(<pyrotech:cobblestone:3>, [[<pyrotech:rock:8>, <pyrotech:rock:8>, <pyrotech:rock:8>], [<pyrotech:rock:8>, <pyrotech:rock:8>, <pyrotech:rock:8>], [<pyrotech:rock:8>, <pyrotech:rock:8>, <pyrotech:rock:8>]]);
recipes.addShaped(<pyrotech:material:35> * 2, [[<minecraft:clay_ball>, <pyrotech:material>, <minecraft:clay_ball>], [<pyrotech:material:8>, <pyrotech:material:3>, <pyrotech:material:8>], [<minecraft:clay_ball>, <pyrotech:material>, <minecraft:clay_ball>]]);
recipes.addShaped(<pyrotech:material:4>, [[<pyrotech:material:35>, <pyrotech:material:25>, <pyrotech:material:35>], [<pyrotech:material:25>, <toughasnails:charcoal_filter>, <pyrotech:material:25>], [<pyrotech:material:35>, <pyrotech:material:25>, <pyrotech:material:35>]]);
recipes.addShaped(<pyrotech:mulch>, [[<pyrotech:rock:7>, <pyrotech:material>, <pyrotech:rock:7>], [<pyrotech:material>, <ore:mulchNitrogen>, <pyrotech:material>], [<pyrotech:rock:7>, <pyrotech:material>, <pyrotech:rock:7>]]);
recipes.addShaped(<pyrotech:bloomery>, [[<pyrotech:refractory_brick_block>, <tconstruct:tool_rod>.withTag({Material: "copper"}), <pyrotech:refractory_brick_block>], [<pyrotech:refractory_brick_block>, <pyrotech:material:23>, <pyrotech:refractory_brick_block>], [<pyrotech:refractory_brick_block>, <pyrotech:refractory_brick_block>, <pyrotech:refractory_brick_block>]]);
recipes.addShaped(<pyrotech:stone_hammer>, [[<pyrotech:material:25>, <pyrotech:material:16>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:16>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_hammer>, [[<pyrotech:material:25>, <pyrotech:material:11>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:11>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_hammer>, [[<pyrotech:material:25>, <pyrotech:material:10>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:10>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:iron_hammer>, [[<pyrotech:material:25>, <minecraft:iron_ingot>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <minecraft:iron_ingot>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:gold_hammer>, [[<pyrotech:material:25>, <minecraft:gold_ingot>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <minecraft:gold_ingot>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:diamond_hammer>, [[<pyrotech:material:25>, <minecraft:diamond>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <minecraft:diamond>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:obsidian_hammer>, [[<pyrotech:material:25>, <pyrotech:material:33>, <pyrotech:material:14>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:33>], [<contenttweaker:tool_stick_a>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bucket_clay_unfired>, [[<pyrotech:material:24>, <pyrotech:material:25>, <pyrotech:material:24>], [<pyrotech:material:25>, <pyrotech:material:24>, <pyrotech:material:25>], [<pyrotech:material:13>, <pyrotech:material:13>, <pyrotech:material:13>]]);
recipes.addShaped(<pyrotech:bucket_wood>, [[<pyrotech:material:12>, <ore:plankWood>, <pyrotech:material:12>], [<ore:plankWood>, <pyrotech:material:12>, <ore:plankWood>]]);
recipes.addShaped(<pyrotech:bucket_stone>, [[<pyrotech:material:16>, <minecraft:clay_ball>, <pyrotech:material:16>], [<minecraft:clay_ball>, <pyrotech:material:16>, <minecraft:clay_ball>]]);
recipes.addShaped(<pyrotech:igniter>, [[<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>], [<minecraft:redstone>, <ore:blockRedstone>, <minecraft:iron_bars>], [<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:igniter:1>, [[<pyrotech:material:5>, <pyrotech:material:5>, <pyrotech:material:5>], [<minecraft:redstone>, <ore:blockRedstone>, <minecraft:iron_bars>], [<pyrotech:material:5>, <pyrotech:material:5>, <pyrotech:material:5>]]);
recipes.addShaped(<pyrotech:torch_stone>, [[<minecraft:coal:*>], [<pyrotech:material:27>], [<pyrotech:material:23>]]);
recipes.addShaped(<pyrotech:bow_drill>, [[<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:26>], [<contenttweaker:tool_stick_a>, <ore:stickWood>, <pyrotech:material:26>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:26>]]);
recipes.addShaped(<pyrotech:matchstick>, [[<pyrotech:rock:7>, <pyrotech:rock:7>, <ore:stone>], [<pyrotech:rock:7>, <contenttweaker:tool_stick_a>, <pyrotech:rock:7>]]);
recipes.addShaped(<pyrotech:shelf>, [[<ore:plankWood>, <ore:slabWood>, <ore:plankWood>], [<ore:plankWood>, <ore:slabWood>, <ore:plankWood>], [<ore:plankWood>, <ore:slabWood>, <ore:plankWood>]]);
recipes.addShaped(<pyrotech:shelf_stone>, [[<pyrotech:material:23>, <pyrotech:material:16>, <pyrotech:material:23>], [<pyrotech:material:16>, <pyrotech:shelf>, <pyrotech:material:16>], [<pyrotech:material:23>, <pyrotech:material:16>, <pyrotech:material:23>]]);
recipes.addShaped(<pyrotech:stash>, [[<ore:slabWood>, <pyrotech:material:25>, <ore:slabWood>], [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:stash_stone>, [[<pyrotech:material:16>, <pyrotech:material:23>, <pyrotech:material:16>], [<pyrotech:material:23>, <pyrotech:stash>, <pyrotech:material:23>], [<pyrotech:material:16>, <pyrotech:material:23>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:crate>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<ore:plankWood>, <ore:slabWood>, <ore:plankWood>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<pyrotech:crate_stone>, [[<pyrotech:material:23>, <pyrotech:material:16>, <pyrotech:material:23>], [<pyrotech:material:16>, <pyrotech:crate>, <pyrotech:material:16>], [<pyrotech:material:23>, <pyrotech:material:16>, <pyrotech:material:23>]]);
recipes.addShaped(<pyrotech:wood_rack>, [[<ore:logWood>, <ore:slabWood>, <ore:logWood>], [<minecraft:ladder>, <ore:slabWood>, <minecraft:ladder>], [<ore:logWood>, <ore:slabWood>, <ore:logWood>]]);
recipes.addShaped(<pyrotech:tank>, [[<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:rock:7>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:tank:1>, [[<pyrotech:material:5>, <ore:blockGlass>, <pyrotech:material:5>], [<ore:blockGlass>, <progressiontweaks:nanomachine_frame>, <ore:blockGlass>], [<pyrotech:material:5>, <ore:blockGlass>, <pyrotech:material:5>]]);
recipes.addShaped(<pyrotech:faucet_stone>, [[<pyrotech:material:16>, <pyrotech:material:25>, <pyrotech:material:16>], [<pyrotech:material:17>, <pyrotech:material:16>, <pyrotech:material:17>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:faucet_brick>, [[<pyrotech:material:5>, <pyrotech:material:25>, <pyrotech:material:5>], [<pyrotech:material:35>, <pyrotech:material:5>, <pyrotech:material:35>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bag_simple>, [[<ore:wool>, <pyrotech:material:14>, <ore:wool>], [<minecraft:leather>, <pyrotech:stash>, <minecraft:leather>], [<pyrotech:material:25>, <minecraft:leather>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bag_durable>, [[<minecraft:leather>, <pyrotech:material:26>, <minecraft:leather>], [<minecraft:leather>, <pyrotech:stash_stone>, <minecraft:leather>], [<minecraft:leather>, <minecraft:gold_ingot>, <minecraft:leather>]]);
recipes.addShaped(<pyrotech:anvil_granite>, [[<pyrotech:rock:7>, <minecraft:stone:1>, <pyrotech:rock:7>], [<pyrotech:rock:7>, <minecraft:stone:5>, <pyrotech:rock:7>], [<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:kiln_pit>, [[<pyrotech:material:13>, <pyrotech:material:13>, <pyrotech:material:13>], [<pyrotech:material:13>, <pyrotech:material:13>, <pyrotech:material:13>], [<pyrotech:material:13>, <pyrotech:material:13>, <pyrotech:material:13>]]);
recipes.addShaped(<pyrotech:drying_rack:1>, [[<contenttweaker:breaking_stick>, <pyrotech:material:14>, <contenttweaker:breaking_stick>], [<pyrotech:material:14>, <minecraft:ladder>, <pyrotech:material:14>], [<contenttweaker:breaking_stick>, <pyrotech:material:14>, <contenttweaker:breaking_stick>]]);
recipes.addShaped(<pyrotech:worktable_stone>, [[<pyrotech:material:16>, <minecraft:stone:5>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:worktable>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:stone_bricks>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:compacting_bin>, [[<ore:stone>, <pyrotech:material:25>, <ore:stone>], [<ore:plankWood>, <pyrotech:material:25>, <ore:plankWood>], [<ore:stone>, <ore:slabWood>, <ore:stone>]]);
recipes.addShaped(<pyrotech:soaking_pot>, [[<pyrotech:material:16>, <pyrotech:rock:7>, <pyrotech:material:16>], [<ore:plankWood>, <pyrotech:material:16>, <ore:plankWood>], [<ore:plankWood>, <pyrotech:material:16>, <ore:plankWood>]]);
recipes.addShaped(<pyrotech:stone_kiln>, [[<pyrotech:stone_bricks>, <pyrotech:material:16>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:kiln_pit>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:stone_bricks>, <pyrotech:stone_bricks>]]);
recipes.addShaped(<pyrotech:stone_oven>, [[<pyrotech:stone_bricks>, <pyrotech:material:16>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:tinder>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:stone_bricks>, <pyrotech:stone_bricks>]]);
recipes.addShaped(<pyrotech:stone_sawmill>, [[<pyrotech:stone_bricks>, <pyrotech:material:16>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:chopping_block>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:stone_bricks>, <pyrotech:stone_bricks>]]);
recipes.addShaped(<pyrotech:stone_crucible>, [[<pyrotech:stone_bricks>, <pyrotech:material:16>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:tank>, <pyrotech:stone_bricks>], [<pyrotech:stone_bricks>, <pyrotech:stone_bricks>, <pyrotech:stone_bricks>]]);
recipes.addShaped(<pyrotech:bellows>, [[<pyrotech:material:20>, <pyrotech:material:16>, <pyrotech:material:20>], [<minecraft:leather>, <pyrotech:material:27>, <minecraft:leather>], [<pyrotech:stone_bricks>, <pyrotech:material:25>, <pyrotech:stone_bricks>]]);
recipes.addShaped(<pyrotech:sawmill_blade_stone>, [[<pyrotech:rock:2>, <pyrotech:rock:2>, <pyrotech:rock:2>], [<pyrotech:rock:2>, <minecraft:stone:3>, <pyrotech:rock:2>], [<pyrotech:rock:2>, <pyrotech:rock:2>, <pyrotech:rock:2>]]);
recipes.addShaped(<pyrotech:sawmill_blade_flint>, [[<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:10>], [<pyrotech:material:10>, <pyrotech:sawmill_blade_stone>, <pyrotech:material:10>], [<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:10>]]);
recipes.addShaped(<pyrotech:sawmill_blade_bone>, [[<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:11>], [<pyrotech:material:11>, <pyrotech:sawmill_blade_flint>, <pyrotech:material:11>], [<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:11>]]);
recipes.addShaped(<pyrotech:sawmill_blade_iron>, [[<pyrotech:material:19>, <minecraft:iron_ingot>, <pyrotech:material:19>], [<minecraft:iron_ingot>, <pyrotech:sawmill_blade_bone>, <minecraft:iron_ingot>], [<pyrotech:material:19>, <minecraft:iron_ingot>, <pyrotech:material:19>]]);
recipes.addShaped(<pyrotech:sawmill_blade_gold>, [[<pyrotech:material:34>, <pyrotech:material:34>, <pyrotech:material:34>], [<pyrotech:material:34>, <pyrotech:sawmill_blade_iron>, <pyrotech:material:34>], [<pyrotech:material:34>, <pyrotech:material:34>, <pyrotech:material:34>]]);
recipes.addShaped(<pyrotech:sawmill_blade_diamond>, [[<pyrotech:material:18>, <pyrotech:material:18>, <pyrotech:material:18>], [<pyrotech:material:18>, <pyrotech:sawmill_blade_gold>, <pyrotech:material:18>], [<pyrotech:material:18>, <pyrotech:material:18>, <pyrotech:material:18>]]);
recipes.addShaped(<pyrotech:sawmill_blade_obsidian>, [[<pyrotech:material:33>, <pyrotech:material:33>, <pyrotech:material:33>], [<pyrotech:material:33>, <pyrotech:sawmill_blade_diamond>, <pyrotech:material:33>], [<pyrotech:material:33>, <pyrotech:material:33>, <pyrotech:material:33>]]);
recipes.addShaped(<pyrotech:cog_wood>, [[<ore:stickWood>, <contenttweaker:breaking_stick>, <ore:stickWood>], [<contenttweaker:breaking_stick>, <ore:plankWood>, <contenttweaker:breaking_stick>], [<ore:stickWood>, <contenttweaker:breaking_stick>, <ore:stickWood>]]);
recipes.addShaped(<pyrotech:cog_stone>, [[<ore:rock>, <pyrotech:material:27>, <ore:rock>], [<pyrotech:material:27>, <pyrotech:cog_wood>, <pyrotech:material:27>], [<ore:rock>, <pyrotech:material:27>, <ore:rock>]]);
recipes.addShaped(<pyrotech:cog_flint>, [[<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:10>], [<pyrotech:material:10>, <pyrotech:cog_stone>, <pyrotech:material:10>], [<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:10>]]);
recipes.addShaped(<pyrotech:cog_bone>, [[<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:11>], [<pyrotech:material:11>, <pyrotech:cog_flint>, <pyrotech:material:11>], [<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:11>]]);
recipes.addShaped(<pyrotech:cog_iron>, [[<pyrotech:material:19>, <pyrotech:material:19>, <pyrotech:material:19>], [<pyrotech:material:19>, <pyrotech:cog_bone>, <pyrotech:material:19>], [<pyrotech:material:19>, <pyrotech:material:19>, <pyrotech:material:19>]]);
recipes.addShaped(<pyrotech:cog_gold>, [[<pyrotech:material:34>, <pyrotech:material:34>, <pyrotech:material:34>], [<pyrotech:material:34>, <pyrotech:cog_iron>, <pyrotech:material:34>], [<pyrotech:material:34>, <pyrotech:material:34>, <pyrotech:material:34>]]);
recipes.addShaped(<pyrotech:cog_diamond>, [[<pyrotech:material:18>, <pyrotech:material:18>, <pyrotech:material:18>], [<pyrotech:material:18>, <pyrotech:cog_gold>, <pyrotech:material:18>], [<pyrotech:material:18>, <pyrotech:material:18>, <pyrotech:material:18>]]);
recipes.addShaped(<pyrotech:cog_obsidian>, [[<pyrotech:material:33>, <pyrotech:material:33>, <pyrotech:material:33>], [<pyrotech:material:33>, <pyrotech:cog_diamond>, <pyrotech:material:33>], [<pyrotech:material:33>, <pyrotech:material:33>, <pyrotech:material:33>]]);
recipes.addShaped(<pyrotech:tar_collector>, [[<pyrotech:material:16>, <pyrotech:material:25>, <pyrotech:material:16>], [<pyrotech:material:16>, <toughasnails:charcoal_filter>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:material:16>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:tar_collector:1>, [[<pyrotech:material:5>, <pyrotech:material:25>, <pyrotech:material:5>], [<pyrotech:material:5>, <toughasnails:charcoal_filter>, <pyrotech:material:5>], [<pyrotech:material:5>, <pyrotech:material:5>, <pyrotech:material:5>]]);
recipes.addShaped(<pyrotech:tar_drain>, [[<pyrotech:material:16>, <pyrotech:rock:7>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:rock:7>, <pyrotech:material:16>], [<pyrotech:material:16>, <pyrotech:rock:7>, <pyrotech:material:16>]]);
recipes.addShaped(<pyrotech:tar_drain:1>, [[<pyrotech:material:5>, <pyrotech:rock:7>, <pyrotech:material:5>], [<pyrotech:material:5>, <pyrotech:rock:7>, <pyrotech:material:5>], [<pyrotech:material:5>, <pyrotech:rock:7>, <pyrotech:material:5>]]);
recipes.addShaped(<pyrotech:bone_axe>, [[<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:11>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_hoe>, [[<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_pickaxe>, [[<pyrotech:material:11>, <pyrotech:material:11>, <pyrotech:material:11>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_shovel>, [[<pyrotech:material:25>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_sword>, [[<pyrotech:material:25>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_axe>, [[<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:10>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_hoe>, [[<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_pickaxe>, [[<pyrotech:material:10>, <pyrotech:material:10>, <pyrotech:material:10>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_shovel>, [[<pyrotech:material:25>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_sword>, [[<pyrotech:material:25>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:25>, <contenttweaker:tool_stick_a>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:unfired_clay_shears>, [[<ore:twine>, <minecraft:clay_ball>, <pyrotech:material:25>], [<minecraft:clay_ball>, <toughasnails:charcoal_filter>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:stone_shears>, [[<ore:twine>, <pyrotech:material:16>, <pyrotech:material:25>], [<pyrotech:material:16>, <toughasnails:charcoal_filter>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:bone_shears>, [[<ore:twine>, <pyrotech:material:11>, <pyrotech:material:25>], [<pyrotech:material:11>, <toughasnails:charcoal_filter>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<pyrotech:flint_shears>, [[<ore:twine>, <pyrotech:material:10>, <pyrotech:material:25>], [<pyrotech:material:10>, <toughasnails:charcoal_filter>, <pyrotech:material:25>], [<pyrotech:material:25>, <pyrotech:material:25>, <pyrotech:material:25>]]);
recipes.addShaped(<toughasnails:charcoal_filter> * 3, [[<minecraft:paper>, <minecraft:paper>, <minecraft:paper>], [<itemfilters:filter>, <ore:charcoal>, <itemfilters:filter>], [<minecraft:paper>, <minecraft:paper>, <minecraft:paper>]]);
recipes.addShaped(<toughasnails:campfire>, [[<contenttweaker:breaking_stick>, <ore:logWood>, <contenttweaker:breaking_stick>], [<ore:logWood>, <pyrotech:tinder>, <ore:logWood>], [<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]]);
recipes.addShaped(<toughasnails:rain_collector>, [[<minecraft:iron_ingot>, <progressiontweaks:nanomachine_frame>, <minecraft:iron_ingot>], [<ore:cobblestone>, <minecraft:bucket>, <ore:cobblestone>], [<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]]);
recipes.addShaped(<toughasnails:temperature_coil>, [[<toughasnails:ice_cube>, <progressiontweaks:nanomachine_frame>, <toughasnails:ice_cube>], [<toughasnails:ice_cube>, <ore:cobblestoneDiorite>, <toughasnails:ice_cube>], [<ore:cobblestoneDiorite>, <ore:blockRedstone>, <ore:cobblestoneDiorite>]]);
recipes.addShaped(<toughasnails:temperature_coil:1>, [[<toughasnails:magma_shard>, <progressiontweaks:nanomachine_frame>, <toughasnails:magma_shard>], [<toughasnails:magma_shard>, <ore:cobblestoneGranite>, <toughasnails:magma_shard>], [<ore:cobblestoneGranite>, <ore:blockRedstone>, <ore:cobblestoneGranite>]]);
recipes.addShaped(<toughasnails:thermometer>, [[<contenttweaker:glue>, <ore:blockGlass>, <contenttweaker:glue>], [<ore:blockGlass>, <progressiontweaks:nanomachine_frame>, <ore:blockGlass>], [<contenttweaker:glue>, <ore:blockGlass>, <contenttweaker:glue>]]);
recipes.addShaped(<minecraft:ladder>, [[<contenttweaker:breaking_stick>, <pyrotech:material:14>, <contenttweaker:breaking_stick>], [<contenttweaker:breaking_stick>, <contenttweaker:breaking_stick>, <contenttweaker:breaking_stick>], [<contenttweaker:breaking_stick>, <pyrotech:material:14>, <contenttweaker:breaking_stick>]]);

//Kiln recipes

mods.pyrotech.PitKiln.addRecipe("randomeo_c", <pyrotech:material:16>, <minecraft:stone>, 2 * 60 * 20, 0.44, [<pyrotech:rock>]);
mods.pyrotech.StoneKiln.addRecipe("randomeo_a", <pyrotech:material:16>, <minecraft:stone>, 3000);

//Anvil recipes
mods.pyrotech.GraniteAnvil.addRecipe("randomeo_b", <pyrotech:material:33>, <minecraft:obsidian>, 8, "hammer");

//Furnace recipes
furnace.addRecipe(<minecraft:bread>, <appliedenergistics2:material:4>);
furnace.addRecipe(<minecraft:baked_potato>, <minecraft:potato>);
furnace.addRecipe(<toughasnails:purified_water_bottle>, <minecraft:potion>.withTag({Potion: "minecraft:water"}));

//Brick oven recipes
mods.pyrotech.BrickOven.addRecipe("randomeo_d", <minecraft:bread>, <appliedenergistics2:material:4>);
mods.pyrotech.BrickOven.addRecipe("randomeo_e", <minecraft:baked_potato>, <minecraft:potato>);
mods.pyrotech.BrickOven.addRecipe("randomeo_f", <toughasnails:purified_water_bottle>, <minecraft:potion>.withTag({Potion: "minecraft:water"}));

//Sawmill recipes
mods.pyrotech.StoneSawmill.addRecipe("randomeo_g", <minecraft:web>, <millenaire:cotton>, 200, <pyrotech:sawmill_blade_stone:*>, 1);
mods.pyrotech.StoneSawmill.addRecipe("randomeo_h", <minecraft:string>, <minecraft:web>, 200, <pyrotech:sawmill_blade_stone:*>, 1);
mods.pyrotech.StoneSawmill.addRecipe("randomeo_hijklmnop", <pyrotech:rock:7> * 2, <minecraft:stick>, 200, <pyrotech:sawmill_blade_flint:*>, 1);

//Compacting bin recipes
mods.pyrotech.CompactingBin.addRecipe("randomeo_i", <minecraft:wool>, <minecraft:string>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_j", <minecraft:melon_block>, <minecraft:melon>, 9);
mods.pyrotech.CompactingBin.addRecipe("randomeo_k", <minecraft:sandstone>, <minecraft:sand>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_l", <minecraft:dirt:1>, <minecraft:dirt>, 9);
mods.pyrotech.CompactingBin.addRecipe("randomeo_m", <geolosys:coal>, <minecraft:coal_block>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_n", <geolosys:coal:1>, <geolosys:coal>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_o", <geolosys:coal:2>, <geolosys:coal:1>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_p", <geolosys:coal:3>, <geolosys:coal:2>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_q", <pyrotech:coal_coke_block>, <pyrotech:material:1>, 9);
mods.pyrotech.CompactingBin.addRecipe("randomeo_r", <millenaire:winebasic>, <millenaire:grapes>, 6);
mods.pyrotech.CompactingBin.addRecipe("randomeo_s", <millenaire:oliveoil>, <millenaire:olives>, 4);
mods.pyrotech.CompactingBin.addRecipe("randomeo_t", <millenaire:cider>, <millenaire:ciderapple>, 6);
mods.pyrotech.CompactingBin.addRecipe("randomeo_u", <millenaire:masa>, <millenaire:maize>, 3);

//Soaking pot recipes
mods.pyrotech.SoakingPot.addRecipe("randomeo_v", <minecraft:mycelium>, <liquid:water> * 1000, <minecraft:grass>, 5 * 60 * 20);
mods.pyrotech.SoakingPot.addRecipe("randomeo_w", <minecraft:slime_ball>, <liquid:water> * 1000, <pyrotech:material:4>, 5 * 60 * 20);
mods.pyrotech.SoakingPot.addRecipe("randomeo_y", <pyrotech:rock_grass>, <liquid:water> * 1000, <pyrotech:rock:4>, 5 * 60 * 20);

//Mortar recipes
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <appliedenergistics2:material:4>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:wheat>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_mushroom>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:1>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:2>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:cactus>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:3>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:brown_mushroom>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:5>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:2>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:6>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:4>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:7>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:8>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:8>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:3>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:9>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:7>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:10>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:sapling>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:11>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:yellow_flower>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:12>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:1>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:13>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:6>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:dye:14>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:red_flower:5>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:melon_seeds>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:melon>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:pumpkin_seeds> * 4, 2, <pyrotech:rock:4>, 0.2, [<minecraft:pumpkin>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:wheat_seeds>, 2, <pyrotech:rock:4>, 0.2, [<pyrotech:material:12>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:beetroot_seeds>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:beetroot>]);
mods.advancedmortars.Mortar.addRecipe(["wood", "stone", "iron", "diamond", "emerald", "gold", "obsidian"], <minecraft:sugar>, 2, <pyrotech:rock:4>, 0.2, [<minecraft:reeds>]);