#Name: zzStagingSpecificItems3.zs
#Author: Austinsupercar

print("Initializing 'zzStagingSpecificItems3'...");

mods.ItemStages.addItemStage("stone", <pyrotech:material:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:5>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:4>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:8>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:9>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:10>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:11>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:16>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:22>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_bricks>); 
mods.ItemStages.addItemStage("stone", <pyrotech:planks_tarred>); 
mods.ItemStages.addItemStage("stone", <pyrotech:farmland_mulched>); 
mods.ItemStages.addItemStage("stone", <pyrotech:pile_ash>); 
mods.ItemStages.addItemStage("stone", <pyrotech:pile_wood_chips>); 
mods.ItemStages.addItemStage("stone", <pyrotech:wool_tarred>); 
mods.ItemStages.addItemStage("stone", <pyrotech:charcoal_block>); 
mods.ItemStages.addItemStage("stone", <pyrotech:wood_tar_block>); 
mods.ItemStages.addItemStage("stone", <pyrotech:living_tar>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_door>); 
mods.ItemStages.addItemStage("stone", <pyrotech:log_pile>); 
mods.ItemStages.addItemStage("stone", <pyrotech:coal_coke_block>); 
mods.ItemStages.addItemStage("stone", <pyrotech:thatch>); 
mods.ItemStages.addItemStage("stone", <pyrotech:refractory_brick_block>); 
mods.ItemStages.addItemStage("stone", <pyrotech:limestone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:fossil_ore>); 
mods.ItemStages.addItemStage("stone", <pyrotech:dense_coal_ore>); 
mods.ItemStages.addItemStage("stone", <pyrotech:dense_nether_coal_ore>); 
mods.ItemStages.addItemStage("stone", <minecraft:brick>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:tool_stick_a>); 
mods.ItemStages.addItemStage("stone", <itemfilters:filter>); 
mods.ItemStages.addItemStage("stone", <pyrotech:fluid.liquid_clay>); 
mods.ItemStages.addItemStage("stone", <pyrotech:refractory_door>); 
mods.ItemStages.addItemStage("stone", <pyrotech:diamond_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:obsidian_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bloomery>); 
mods.ItemStages.addItemStage("stone", <pyrotech:pile_slag>); 
mods.ItemStages.addItemStage("stone", <pyrotech:slag>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_flint>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_bone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_iron>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:18>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:19>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:23>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:24>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:6>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:7>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:26>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:27>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:28>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:30>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:32>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:33>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:34>); 
mods.ItemStages.addItemStage("stone", <pyrotech:material:35>); 
mods.ItemStages.addItemStage("stone", <pyrotech:mulch>); 
mods.ItemStages.addItemStage("stone", <pyrotech:apple_baked>); 
mods.ItemStages.addItemStage("stone", <pyrotech:carrot_roasted>); 
mods.ItemStages.addItemStage("stone", <pyrotech:egg_roasted>); 
mods.ItemStages.addItemStage("stone", <pyrotech:mushroom_brown_roasted>); 
mods.ItemStages.addItemStage("stone", <pyrotech:mushroom_red_roasted>); 
mods.ItemStages.addItemStage("stone", <pyrotech:beetroot_roasted>); 
mods.ItemStages.addItemStage("stone", <pyrotech:fluid.wood_tar>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:iron_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:gold_hammer>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_silver>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_silver>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_tin>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_tin>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_uranium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_uranium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bucket_clay>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bucket_clay_unfired>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bucket_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_gold>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_diamond>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tongs_obsidian>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_aluminum>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_aluminum>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_ardite>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_ardite>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_cobalt>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_cobalt>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_copper>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_copper>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_gold>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_gold>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_iridium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_iridium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_iron>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_iron>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_lead>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_lead>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_mithril>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_mithril>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_nickel>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_nickel>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_osmium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_osmium>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_slag_platinum>); 
mods.ItemStages.addItemStage("stone", <pyrotech:generated_pile_slag_platinum>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_iron>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_gold>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_diamond>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_obsidian>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_wood>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_flint>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_bone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_iron>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_bone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_flint>); 
mods.ItemStages.addItemStage("stone", <pyrotech:sawmill_blade_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_axe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_oven>); 
mods.ItemStages.addItemStage("stone", <pyrotech:fluid.coal_tar>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_kiln>); 
mods.ItemStages.addItemStage("stone", <pyrotech:worktable_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:anvil_granite>); 
mods.ItemStages.addItemStage("stone", <pyrotech:igniter>); 
mods.ItemStages.addItemStage("stone", <pyrotech:igniter:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:torch_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:matchstick>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bow_drill>); 
mods.ItemStages.addItemStage("stone", <pyrotech:shelf>); 
mods.ItemStages.addItemStage("stone", <pyrotech:shelf_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stash>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stash_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:crate_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:wood_rack>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tank>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tank:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:drying_rack:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:faucet_stone>); 
mods.ItemStages.addItemStage("stone", <pyrotech:faucet_brick>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bag_simple>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bag_durable>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_gold>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_diamond>); 
mods.ItemStages.addItemStage("stone", <pyrotech:cog_obsidian>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_sawmill>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_crucible>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bellows>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tar_collector>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tar_collector:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tar_drain>); 
mods.ItemStages.addItemStage("stone", <pyrotech:tar_drain:1>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_hoe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_pickaxe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_shovel>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_sword>); 
mods.ItemStages.addItemStage("stone", <pyrotech:clay_shears>); 
mods.ItemStages.addItemStage("stone", <pyrotech:unfired_clay_shears>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_axe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_hoe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_pickaxe>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_shovel>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_sword>); 
mods.ItemStages.addItemStage("stone", <pyrotech:bone_shears>); 
mods.ItemStages.addItemStage("stone", <pyrotech:stone_shears>); 
mods.ItemStages.addItemStage("stone", <pyrotech:flint_shears>); 

mods.ItemStages.addItemStage("copper", <contenttweaker:tool_stick_b>); 
mods.ItemStages.addItemStage("electrical", <pyrotech:wither_forge>); 
mods.ItemStages.addItemStage("electrical", <pyrotech:mechanical_compacting_bin>); 
mods.ItemStages.addItemStage("electrical", <pyrotech:mechanical_mulch_spreader>); 
mods.ItemStages.addItemStage("electrical", <pyrotech:mechanical_bellows>); 
mods.ItemStages.addItemStage("iron", <pyrotech:mechanical_hopper>); 
mods.ItemStages.addItemStage("copper", <pyrotech:brick_kiln>); 
mods.ItemStages.addItemStage("copper", <pyrotech:brick_oven>); 
mods.ItemStages.addItemStage("copper", <pyrotech:brick_crucible>); 

mods.ItemStages.addItemStage("iron", <conarm:armorforge>.withTag({textureBlock: {ForgeCaps: {"customnpcs:itemscripteddata": {}}, id: "railcraft:metal", Count: 1 as byte, Damage: 8 as short}})); 
mods.ItemStages.addItemStage("iron", <conarm:armorforge>.withTag({textureBlock: {ForgeCaps: {"customnpcs:itemscripteddata": {}}, id: "railcraft:metal", Count: 1 as byte, Damage: 9 as short}})); 
mods.ItemStages.addItemStage("iron", <contenttweaker:glue>); 
mods.ItemStages.addItemStage("iron", <pyrotech:anvil_iron_plated>); 
mods.ItemStages.addItemStage("iron", <pyrotech:gold_shears>); 
mods.ItemStages.addItemStage("iron", <pyrotech:diamond_shears>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_axe>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_hoe>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_pickaxe>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_shovel>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_sword>); 
mods.ItemStages.addItemStage("iron", <pyrotech:obsidian_shears>); 
mods.ItemStages.addItemStage("iron", <tconstruct:toolforge>.withTag({textureBlock: {ForgeCaps: {"customnpcs:itemscripteddata": {}}, id: "railcraft:metal", Count: 1 as byte, Damage: 9 as short}})); 
mods.ItemStages.addItemStage("iron", <tconstruct:toolforge>.withTag({textureBlock: {ForgeCaps: {"customnpcs:itemscripteddata": {}}, id: "railcraft:metal", Count: 1 as byte, Damage: 8 as short}})); 
mods.ItemStages.addItemStage("iron", <tconstruct:bolt>.withTag({StatsOriginal: {AttackSpeedMultiplier: 1.0 as float, Accuracy: 1.0 as float, MiningSpeed: 7.5 as float, FreeModifiers: 3, Durability: 2240, HarvestLevel: 2, Attack: 5.5 as float}, Stats: {AttackSpeedMultiplier: 1.0 as float, Accuracy: 1.0 as float, MiningSpeed: 7.5 as float, FreeModifiers: 3, Durability: 2240, HarvestLevel: 2, Attack: 5.5 as float}, Special: {Categories: ["tool", "projectile", "no_melee"]}, TinkerData: {Materials: ["wood", "integrationforegoing.reinforced_pink_slime", "feather"], Modifiers: []}, Modifiers: [{identifier: "ecological", color: -7444965, level: 1}, {identifier: "slimey_pink", color: -4032074, level: 1}, {identifier: "dense", color: -4032074, level: 1}], Traits: ["ecological", "slimey_pink", "dense"]})); 

mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 0, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 1, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 2, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 3, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 4, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 5, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 6, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 7, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 8, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 9, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 10, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 11, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 12, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 13, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 14, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 15, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 16, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 17, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 18, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 19, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 20, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 21, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 22, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 23, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 24, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 25, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 26, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 27, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 28, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 29, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 30, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 31, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 32, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 33, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 34, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 35, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 36, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 37, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 38, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 39, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 40, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 41, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 42, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 43, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 44, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 45, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 46, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 47, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 48, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 49, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 50, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 51, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 52, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 53, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 54, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 55, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 56, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 57, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 58, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 59, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 60, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 61, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 62, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 63, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 64, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 65, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 66, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 67, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 68, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 69, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 70, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 71, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 72, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 73, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 74, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 75, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 76, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 77, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 78, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 79, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 80, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 81, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 82, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 83, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 84, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 85, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 86, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 87, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 88, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 89, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 90, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 91, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 92, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <architecturecraft:shape>.withTag({Shape: 93, BaseName: "minecraft:planks", BaseData: 0})); 
mods.ItemStages.addItemStage("electrical", <contenttweaker:super_diamond>); 
mods.ItemStages.addItemStage("electrical", <contenttweaker:oil_ingot>); 

mods.ItemStages.addItemStage("industrial", <contenttweaker:gem_h>); 
mods.ItemStages.addItemStage("industrial", <avaritia:block_resource:2>); 
mods.ItemStages.addItemStage("industrial", <avaritia:resource:1>); 
mods.ItemStages.addItemStage("industrial", <avaritia:resource>); 

mods.ItemStages.addItemStage("modern", <contenttweaker:gem_i>); 
mods.ItemStages.addItemStage("modern", <ocsensors:sensor>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:base_addon>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:energy_tier1>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:energy_tier2>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:machine_case>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:speed_tier1>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:speed_tier2>); 
mods.ItemStages.addItemStage("modern", <teslacorelib:wrench>); 

mods.ItemStages.addItemStage("exploration", <contenttweaker:charging_gem>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:diamond_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:void_block>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:gold_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:gold_grass>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_diamond>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_coal>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:red_obsidian>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deepest_ore>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:locked_dungeon_block:1>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:locked_dungeon_block:2>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:locked_dungeon_block:3>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:locked_dungeon_block:4>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:locked_dungeon_block:5>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:dungeon_trap:1>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:dungeon_trap:2>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:dungeon_trap:3>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:dungeon_trap:4>); 
mods.ItemStages.addItemStage("exploration", <aether_legacy:dungeon_trap:5>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_copper>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_lapis>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deep_cobalt>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:code_ore_b>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:code_ore_c>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:blue_obsidian>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:code_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:broken_cobblestone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:code_ore_d>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deeper_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deep_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deeperer_stone>); 
mods.ItemStages.addItemStage("modern", <contenttweaker:inner_stomach_wall>); 
mods.ItemStages.addItemStage("modern", <contenttweaker:outer_stomach_wall>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:sign_d>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:sign_e>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:red_compound_ingot>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_redstone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:diamond_dirt>); 
mods.ItemStages.addItemStage("modern", <contenttweaker:sinking_stomach_wall>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deep_ore>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:iron_dirt>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:code_ore>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:raw_unobtainium_gem>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_cobalt>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deep_diamond>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:mos_ore>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:iron_grass>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deepest_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:diamond_grass>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:corrupted_soul_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:unobtainium_ore>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:gold_dirt>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:green_ore>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_iron>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_gold>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:broken_bedrock>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:iron_stone>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_emerald>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:compressed_tin>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:unobtainium>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:mos_ingot>); 
mods.ItemStages.addItemStage("exploration", <contenttweaker:deepest_ingot>); 

mods.ItemStages.addItemStage("atomic", <minecraft:dragon_breath>); 
mods.ItemStages.addItemStage("atomic", <minecraft:spectral_arrow>); 
mods.ItemStages.addItemStage("atomic", <minecraft:totem_of_undying>); 
mods.ItemStages.addItemStage("atomic", <minecraft:mob_spawner>); 
mods.ItemStages.addItemStage("atomic", <minecraft:brown_mushroom_block>); 
mods.ItemStages.addItemStage("atomic", <minecraft:red_mushroom_block>); 
mods.ItemStages.addItemStage("atomic", <minecraft:barrier>); 
mods.ItemStages.addItemStage("atomic", <minecraft:structure_void>); 
mods.ItemStages.addItemStage("atomic", <contenttweaker:gem_j>); 
mods.ItemStages.addItemStage("atomic", <contenttweaker:gem_f>); 
mods.ItemStages.addItemStage("atomic", <contenttweaker:gem_d>); 
mods.ItemStages.addItemStage("atomic", <contenttweaker:gem_b>); 
mods.ItemStages.addItemStage("atomic", <contenttweaker:sign_f>); 

mods.ItemStages.addItemStage("fusion", <avaritia:resource:2>); 
mods.ItemStages.addItemStage("fusion", <avaritia:resource:3>); 
mods.ItemStages.addItemStage("fusion", <avaritia:resource:4>); 
mods.ItemStages.addItemStage("fusion", <avaritia:block_resource>); 
mods.ItemStages.addItemStage("fusion", <contenttweaker:gem_e>); 
mods.ItemStages.addItemStage("fusion", <contenttweaker:gem_a>); 
mods.ItemStages.addItemStage("fusion", <contenttweaker:iridium_infused_uranium_ingot>); 
mods.ItemStages.addItemStage("fusion", <contenttweaker:strong_iridium_infused_uranium_ingot>); 

mods.ItemStages.addItemStage("copper", <contenttweaker:sign_q>); 
mods.ItemStages.addItemStage("emc", <contenttweaker:gem_g>); 
mods.ItemStages.addItemStage("emc", <contenttweaker:mos_neutronium_compound_ingot>); 

mods.ItemStages.addItemStage("draconic", <avaritia:resource:5>); 
mods.ItemStages.addItemStage("draconic", <avaritia:resource:6>); 
mods.ItemStages.addItemStage("draconic", <avaritia:endest_pearl>); 
mods.ItemStages.addItemStage("draconic", <avaritia:ultimate_stew>); 
mods.ItemStages.addItemStage("draconic", <avaritia:cosmic_meatballs>); 
mods.ItemStages.addItemStage("draconic", <avaritia:block_resource:1>); 
mods.ItemStages.addItemStage("draconic", <avaritia:resource:7>); 
mods.ItemStages.addItemStage("draconic", <contenttweaker:super_flint>); 
mods.ItemStages.addItemStage("draconic", <contenttweaker:gem_c>); 

mods.ItemStages.addItemStage("infinity", <ftbquests:custom_icon>.withTag({icon: "ftblib:textures/icons/support.png"})); 
mods.ItemStages.addItemStage("infinity", <forestry:greenhouse:3>); 
mods.ItemStages.addItemStage("infinity", <forestry:greenhouse:4>); 
mods.ItemStages.addItemStage("infinity", <forestry:greenhouse:5>); 
mods.ItemStages.addItemStage("infinity", <forestry:climatiser:1>); 
mods.ItemStages.addItemStage("infinity", <forestry:climatiser:2>); 
mods.ItemStages.addItemStage("infinity", <forestry:climatiser:3>); 
mods.ItemStages.addItemStage("infinity", <forestry:climatiser:4>); 
mods.ItemStages.addItemStage("infinity", <landmanager:admin>); 
mods.ItemStages.addItemStage("infinity", <avaritia:matter_cluster>); 
mods.ItemStages.addItemStage("infinity", <base:wrench>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_a>); 
mods.ItemStages.addItemStage("emc", <contenttweaker:sign_c>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_o>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_n>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_p>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_r>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:sign_s>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 1 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:screen>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 4 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_detector>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:detector>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:detector:1>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 2 as byte, id: "ftbquests:progress_screen_core", Width: 1 as byte}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 8 as byte, id: "ftbquests:progress_screen_core", Width: 4 as byte}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 3 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}})); 
mods.ItemStages.addItemStage("infinity", <ftbquests:loot_crate_storage>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:loot_crate_opener>); 
mods.ItemStages.addItemStage("infinity", <ftbquests:barrier>); 
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 13 as short}]})); 
mods.ItemStages.addItemStage("infinity", <pyrotech:brick_sawmill>); 
mods.ItemStages.addItemStage("infinity", <itemfilters:missing>); 
mods.ItemStages.addItemStage("infinity", <landmanager:home>);
mods.ItemStages.removeItemStage(<rockhounding_chemistry:machines_e:14>);
mods.ItemStages.addItemStage("infinity", <rockhounding_chemistry:machines_e:14>); 
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 37 as short}]})); 

mods.ItemStages.removeItemStage(<millenaire:denier>);
mods.ItemStages.removeItemStage(<millenaire:denierargent>);
mods.ItemStages.removeItemStage(<millenaire:denieror>);
mods.ItemStages.removeItemStage(<appliedenergistics2:material:4>);
mods.ItemStages.addItemStage("stone", <appliedenergistics2:material:4>); 
mods.ItemStages.removeItemStage(<tconstruct:tool_rod>.withTag({Material: "copper"}));
mods.ItemStages.addItemStage("copper", <tconstruct:tool_rod>.withTag({Material: "copper"})); 
mods.ItemStages.removeItemStage(<immersiveengineering:metal:29>);
mods.ItemStages.removeItemStage(<mekanism:salt>);
mods.ItemStages.addItemStage("copper", <immersiveengineering:metal:29>); 
mods.ItemStages.addItemStage("stone", <mekanism:salt>); 

mods.ItemStages.removeItemStage(<immersiveengineering:metal:8>);
mods.ItemStages.addItemStage("iron", <immersiveengineering:metal:8>); 

mods.ItemStages.removeItemStage(<thermalfoundation:material:162>);
mods.ItemStages.addItemStage("industrial", <thermalfoundation:material:162>); 

mods.ItemStages.removeItemStage(<thermalfoundation:material:70>);
mods.ItemStages.addItemStage("industrial", <thermalfoundation:material:70>); 

mods.ItemStages.removeItemStage(<better_diving:copper_ore>);
mods.ItemStages.addItemStage("copper", <better_diving:copper_ore>);
mods.ItemStages.removeItemStage(<better_diving:standard_o2_tank>);
mods.ItemStages.addItemStage("copper", <better_diving:standard_o2_tank>);
mods.ItemStages.removeItemStage(<better_diving:diving_mask>);
mods.ItemStages.addItemStage("copper", <better_diving:diving_mask>);

<contenttweaker:sign_b>.addTooltip(format.green("Place in your off hand and dive underwater"));
<contenttweaker:sign_b>.addTooltip(format.green("Made out of a strange material"));

mods.ItemStages.removeItemStage(<dynamictrees:oakseed>);
mods.ItemStages.removeItemStage(<dynamictrees:spruceseed>);
mods.ItemStages.removeItemStage(<dynamictrees:birchseed>);
mods.ItemStages.removeItemStage(<dynamictrees:jungleseed>);
mods.ItemStages.removeItemStage(<dynamictrees:acaciaseed>);
mods.ItemStages.removeItemStage(<dynamictrees:darkoakseed>);
mods.ItemStages.removeItemStage(<props:props:1688>);
mods.ItemStages.removeItemStage(<minecraft:dye:15>);

mods.ItemStages.addItemStage("stone", <contenttweaker:red_granite_rock>);
mods.ItemStages.addItemStage("stone", <contenttweaker:black_granite_rock>);
mods.ItemStages.addItemStage("stone", <contenttweaker:rhyolite_rock> ); 
mods.ItemStages.addItemStage("stone", <contenttweaker:andesite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:gabbro_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:basalt_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:komatiite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:dacite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:gneiss_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:eclogite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:marble_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:quartzite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:blueschist_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:greenschist_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:soapstone_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:limestone_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:chalk_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:shale_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:siltstone_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:lignite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:dolomite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:greywacke_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:chert_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:migmatite_rock>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_netherrack>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_red_sandstone>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_sandstone>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_andesite>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_diorite>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_granite>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_endstone>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:rock_stone>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:gem_emerald>); 
mods.ItemStages.addItemStage("stone", <contenttweaker:gem_diamond>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:crate_a>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:crate_c>); 
mods.ItemStages.addItemStage("infinity", <contenttweaker:crate_b>); 
mods.ItemStages.addItemStage("modern", <contenttweaker:partly_digested_flesh>);
mods.ItemStages.addItemStage("modern", <contenttweaker:partly_digested_plant>);
mods.ItemStages.addItemStage("modern", <contenttweaker:partly_digested_matter_silicon_infused>);
mods.ItemStages.addItemStage("modern", <contenttweaker:partly_digested_matter_suivyxium_infused>);
mods.ItemStages.addItemStage("modern", <contenttweaker:partly_digested_matter_herobrine_infused>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_plant_chime>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime_c>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime_d>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime_b>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime_f>);
mods.ItemStages.addItemStage("modern", <contenttweaker:lump_of_chime_e>);
mods.ItemStages.addItemStage("modern", <contenttweaker:broken_down_organic_matter>);
mods.ItemStages.addItemStage("modern", <contenttweaker:sinking_stomach_wall>);
mods.ItemStages.addItemStage("modern", <contenttweaker:inner_stomach_wall>);
mods.ItemStages.addItemStage("modern", <contenttweaker:outer_stomach_wall>);
mods.ItemStages.addItemStage("modern", <contenttweaker:sinking_stomach_wall_sil>);
mods.ItemStages.addItemStage("modern", <contenttweaker:inner_stomach_wall_sil>);
mods.ItemStages.addItemStage("modern", <contenttweaker:outer_stomach_wall_sil>);
mods.ItemStages.addItemStage("modern", <contenttweaker:sinking_stomach_wall_su>);
mods.ItemStages.addItemStage("modern", <contenttweaker:inner_stomach_wall_su>);
mods.ItemStages.addItemStage("modern", <contenttweaker:outer_stomach_wall_su>);
mods.ItemStages.addItemStage("modern", <contenttweaker:sinking_stomach_wall_h>);
mods.ItemStages.addItemStage("modern", <contenttweaker:inner_stomach_wall_h>);
mods.ItemStages.addItemStage("modern", <contenttweaker:outer_stomach_wall_h>);

mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 26 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 29 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 29 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 29 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 37 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 37 as short}]}));
mods.ItemStages.removeItemStage(<nuclearcraft:geiger_counter>);
mods.ItemStages.removeItemStage(<nuclearcraft:rad_x>);
mods.ItemStages.removeItemStage(<better_diving:peeper>);
mods.ItemStages.removeItemStage(<better_diving:peeper_cooked>);
mods.ItemStages.removeItemStage(<better_diving:peeper_cured>);
mods.ItemStages.removeItemStage(<better_diving:bladderfish>);
mods.ItemStages.removeItemStage(<better_diving:bladderfish_cooked>);
mods.ItemStages.removeItemStage(<better_diving:bladderfish_cured>);
mods.ItemStages.removeItemStage(<better_diving:garryfish>);
mods.ItemStages.removeItemStage(<better_diving:garryfish_cooked>);
mods.ItemStages.removeItemStage(<better_diving:garryfish_cured>);
mods.ItemStages.removeItemStage(<better_diving:holefish>);
mods.ItemStages.removeItemStage(<better_diving:holefish_cooked>);
mods.ItemStages.removeItemStage(<better_diving:holefish_cured>);
mods.ItemStages.removeItemStage(<better_diving:boomerang>);
mods.ItemStages.removeItemStage(<better_diving:boomerang_cooked>);
mods.ItemStages.removeItemStage(<better_diving:boomerang_cured>);
mods.ItemStages.removeItemStage(<immersiveengineering:material:4>);
mods.ItemStages.removeItemStage(<immersiveengineering:seed>);

mods.ItemStages.addItemStage("stone", <better_diving:peeper>); 
mods.ItemStages.addItemStage("stone", <better_diving:peeper_cooked>); 
mods.ItemStages.addItemStage("stone", <better_diving:peeper_cured>); 
mods.ItemStages.addItemStage("stone", <better_diving:bladderfish>); 
mods.ItemStages.addItemStage("stone", <better_diving:bladderfish_cooked>); 
mods.ItemStages.addItemStage("stone", <better_diving:bladderfish_cured>); 
mods.ItemStages.addItemStage("stone", <better_diving:garryfish>); 
mods.ItemStages.addItemStage("stone", <better_diving:garryfish_cooked>); 
mods.ItemStages.addItemStage("stone", <better_diving:garryfish_cured>); 
mods.ItemStages.addItemStage("stone", <better_diving:holefish>); 
mods.ItemStages.addItemStage("stone", <better_diving:holefish_cooked>); 
mods.ItemStages.addItemStage("stone", <better_diving:holefish_cured>); 
mods.ItemStages.addItemStage("stone", <better_diving:boomerang>); 
mods.ItemStages.addItemStage("stone", <better_diving:boomerang_cooked>); 
mods.ItemStages.addItemStage("stone", <better_diving:boomerang_cured>); 
mods.ItemStages.addItemStage("stone", <immersiveengineering:material:4>); 
mods.ItemStages.addItemStage("stone", <immersiveengineering:seed>);

mods.ItemStages.removeItemStage(<bionisation3:dillbunch>);
mods.ItemStages.removeItemStage(<bionisation3:yarrowseed>);
mods.ItemStages.removeItemStage(<bionisation3:yarrowbunch>);
mods.ItemStages.removeItemStage(<bionisation3:guidebook>);
mods.ItemStages.removeItemStage(<bionisation3:chickenhead>);
mods.ItemStages.removeItemStage(<bionisation3:spectraldust>);
mods.ItemStages.removeItemStage(<bionisation3:glowingliquid>);
mods.ItemStages.removeItemStage(<bionisation3:spiderleg>);
mods.ItemStages.removeItemStage(<bionisation3:darkheart>);
mods.ItemStages.removeItemStage(<bionisation3:guardianbrain>);
mods.ItemStages.removeItemStage(<bionisation3:strangeliquid>);
mods.ItemStages.removeItemStage(<bionisation3:batwing>);
mods.ItemStages.removeItemStage(<bionisation3:wolfstooth>);
mods.ItemStages.removeItemStage(<bionisation3:endersubstance>);
mods.ItemStages.removeItemStage(<bionisation3:blazecore>);
mods.ItemStages.removeItemStage(<bionisation3:heartofcreeper>);
mods.ItemStages.removeItemStage(<bionisation3:dillseed>);
mods.ItemStages.removeItemStage(<bionisation3:garlicbulb>);
mods.ItemStages.removeItemStage(<bionisation3:livingbone>);
mods.ItemStages.removeItemStage(<bionisation3:lotus>);
mods.ItemStages.removeItemStage(<bionisation3:ancientflower>);
mods.ItemStages.removeItemStage(<bionisation3:desertflower>);
mods.ItemStages.removeItemStage(<bionisation3:phoenixflower>);
mods.ItemStages.removeItemStage(<bionisation3:enderflower>);
mods.ItemStages.removeItemStage(<bionisation3:potioncure>.withTag({bionisation3bcure_id: 102}));
mods.ItemStages.removeItemStage(<bionisation3:potioncure>.withTag({bionisation3bcure_id: 110}));

mods.ItemStages.addItemStage("stone", <bionisation3:dillbunch>);
mods.ItemStages.addItemStage("stone", <bionisation3:yarrowseed>);
mods.ItemStages.addItemStage("stone", <bionisation3:yarrowbunch>);
mods.ItemStages.addItemStage("stone", <bionisation3:guidebook>);
mods.ItemStages.addItemStage("stone", <bionisation3:chickenhead>);
mods.ItemStages.addItemStage("copper", <bionisation3:spectraldust>);
mods.ItemStages.addItemStage("copper", <bionisation3:glowingliquid>);
mods.ItemStages.addItemStage("stone", <bionisation3:spiderleg>);
mods.ItemStages.addItemStage("stone", <bionisation3:darkheart>);
mods.ItemStages.addItemStage("copper", <bionisation3:guardianbrain>);
mods.ItemStages.addItemStage("copper", <bionisation3:strangeliquid>);
mods.ItemStages.addItemStage("stone", <bionisation3:batwing>);
mods.ItemStages.addItemStage("stone", <bionisation3:wolfstooth>);
mods.ItemStages.addItemStage("copper", <bionisation3:endersubstance>);
mods.ItemStages.addItemStage("copper", <bionisation3:blazecore>);
mods.ItemStages.addItemStage("stone", <bionisation3:heartofcreeper>);
mods.ItemStages.addItemStage("stone", <bionisation3:dillseed>);
mods.ItemStages.addItemStage("stone", <bionisation3:garlicbulb>);
mods.ItemStages.addItemStage("stone", <bionisation3:livingbone>);
mods.ItemStages.addItemStage("stone", <bionisation3:lotus>);
mods.ItemStages.addItemStage("copper", <bionisation3:ancientflower>);
mods.ItemStages.addItemStage("stone", <bionisation3:desertflower>);
mods.ItemStages.addItemStage("copper", <bionisation3:phoenixflower>);
mods.ItemStages.addItemStage("copper", <bionisation3:enderflower>);
mods.ItemStages.addItemStage("stone", <bionisation3:potioncure>.withTag({bionisation3bcure_id: 102}));
mods.ItemStages.addItemStage("stone", <bionisation3:potioncure>.withTag({bionisation3bcure_id: 110}));
mods.ItemStages.removeItemStage(<immersiveengineering:ore:1>);
mods.ItemStages.addItemStage("iron", <immersiveengineering:ore:1>);
mods.ItemStages.removeItemStage(<bionisation3:guidebook>);

mods.ItemStages.removeItemStage(<adpother:iron_filter>);
mods.ItemStages.removeItemStage(<adpother:gold_filter>);
mods.ItemStages.removeItemStage(<adpother:diamond_filter>);

mods.ItemStages.addItemStage("iron", <adpother:iron_filter>);
mods.ItemStages.addItemStage("iron", <adpother:gold_filter>);
mods.ItemStages.addItemStage("iron", <adpother:diamond_filter>);
mods.ItemStages.removeItemStage(<tconstruct:edible:3>);
mods.ItemStages.removeItemStage(<aether_legacy:aether_portal_frame>);
mods.ItemStages.addItemStage("stone", <tconstruct:edible:3>);

mods.ItemStages.addItemStage("modern", <weather2:pocket_sand>);
mods.ItemStages.addItemStage("modern", <weather2:weather_item>);
mods.ItemStages.addItemStage("modern", <weather2:sand_layer_placeable>);
mods.ItemStages.addItemStage("modern", <weather2:anemometer>);
mods.ItemStages.addItemStage("modern", <weather2:weather_deflector>);
mods.ItemStages.addItemStage("modern", <weather2:weather_machine>);
mods.ItemStages.addItemStage("modern", <weather2:weather_forecast>);
mods.ItemStages.addItemStage("modern", <weather2:wind_vane>);
mods.ItemStages.addItemStage("modern", <weather2:tornado_siren_manual>);
mods.ItemStages.addItemStage("modern", <weather2:tornado_sensor>);
mods.ItemStages.addItemStage("modern", <weather2:tornado_siren>);
mods.ItemStages.addItemStage("modern", <coroutil:item_repairing_gel>);
mods.ItemStages.addItemStage("modern", <coroutil:repairing_block>);