#Name: zzStagingSpecificItems2.zs
#Author: Austinsupercar

print("Initializing 'zzStagingSpecificItems2'...");

mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "plan9k"}, "oc:color": 1, display: {Name: "Plan9k (Operating System)"}, "oc:lootFactory": "opencomputers:plan9k"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "network"}, "oc:color": 10, display: {Name: "Network (Network Stack)"}, "oc:lootFactory": "opencomputers:network"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "openos"}, "oc:color": 2, display: {Name: "OpenOS (Operating System)"}, "oc:lootFactory": "opencomputers:openos"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "data"}, "oc:color": 9, display: {Name: "Data Card Software"}, "oc:lootFactory": "opencomputers:data"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "openloader"}, "oc:color": 13, display: {Name: "OpenLoader (Boot Loader)"}, "oc:lootFactory": "opencomputers:openloader"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "generator"}, "oc:color": 5, display: {Name: "Generator Upgrade Software"}, "oc:lootFactory": "opencomputers:generator"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "oppm"}, "oc:color": 6, display: {Name: "OPPM (Package Manager)"}, "oc:lootFactory": "opencomputers:oppm"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "irc"}, "oc:color": 12, display: {Name: "OpenIRC (IRC Client)"}, "oc:lootFactory": "opencomputers:irc"}));
mods.ItemStages.addItemStage("modern", <opencomputers:card:*>);
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "builder"}, "oc:color": 11, display: {Name: "Builder"}, "oc:lootFactory": "opencomputers:builder"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "maze"}, "oc:color": 14, display: {Name: "Mazer"}, "oc:lootFactory": "opencomputers:maze"}));
mods.ItemStages.addItemStage("modern", <opencomputers:storage:1>.withTag({"oc:data": {"oc:fs.label": "dig"}, "oc:color": 3, display: {Name: "Digger"}, "oc:lootFactory": "opencomputers:dig"}));

mods.ItemStages.addItemStage("atomic", <ore:record>);

mods.ItemStages.addItemStage("draconic", <minecraft:spawn_egg:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:dragon_egg:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:shulker_shell:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:singularity:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:compressed_crafting_table:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:double_compressed_crafting_table:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:extreme_crafting_table:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:neutron_collector:*>);
mods.ItemStages.addItemStage("draconic", <avaritia:neutronium_compressor:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:chorus_fruit:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:chorus_fruit_popped:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:elytra:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:pink_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:yellow_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:light_blue_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:black_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:chorus_flower:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:chorus_plant:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:end_rod:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:end_crystal:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:gray_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:silver_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:lime_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:purple_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:blue_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:cyan_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:brown_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:green_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:red_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:magenta_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:white_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:orange_shulker_box:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:end_portal_frame:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:ender_chest:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:purpur_block:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:purpur_pillar:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:purpur_stairs:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:purpur_slab:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:end_bricks:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:bedrock:*>);
mods.ItemStages.addItemStage("draconic", <minecraft:end_stone:*>);

//Infinity

mods.ItemStages.addItemStage("infinity", <avaritia:infinity_helmet:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_chestplate:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_pants:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:command_block_minecart:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:knowledge_book:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:structure_block:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:repeating_command_block:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:command_block:*>);
mods.ItemStages.addItemStage("infinity", <minecraft:chain_command_block:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:skullfire_sword:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_sword:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_hoe:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_boots:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_axe:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_shovel:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_pickaxe>.withTag({ench: [{lvl: 10 as short, id: 35 as short}]}));
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_bow:*>);
mods.ItemStages.addItemStage("infinity", <avaritia:infinity_pickaxe:*>);

mods.ItemStages.addItemStage("infinity", <minecraft:enchanting_table>);
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 1 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 1 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 1 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 1 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 0 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 0 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 0 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 0 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:experience_bottle>);
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 7 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 4 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 2 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 2 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 4 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 8 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 8 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 4 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 2 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 5 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 8 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 9 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 5 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 3 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 3 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 5 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 9 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 16 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 10 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 6 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 7 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 7 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 4 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 3 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 3 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 18 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 21 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 32 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 16 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 16 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 32 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 16 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 16 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 17 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 17 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 17 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 17 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 17 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 32 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 32 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 32 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 22 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 22 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 22 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 21 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 21 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 18 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 18 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 18 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 18 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 19 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 20 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 20 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 19 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 33 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 48 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 48 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 35 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 35 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 35 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 34 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 34 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 34 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 14 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 61 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 48 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 48 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 62 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 14 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 15 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 62 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 48 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 49 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 62 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 15 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 15 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 70 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 49 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 50 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 71 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 23 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 23 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>);
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 51 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 61 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 14 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 23 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 61 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 14 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 23 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 24 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 24 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 24 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 24 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 26 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 27 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 27 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 27 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 28 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 28 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 28 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 11 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 11 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 11 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 11 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 11 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 13 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 13 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 13 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 12 as short}]}));
mods.ItemStages.addItemStage("infinity", <industrialforegoing:enchantment_aplicator>);
mods.ItemStages.addItemStage("infinity", <industrialforegoing:enchantment_extractor>);
mods.ItemStages.addItemStage("infinity", <industrialforegoing:enchantment_refiner>);
mods.ItemStages.addItemStage("infinity", <draconicevolution:diss_enchanter>);
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 13 as short}]}));
mods.ItemStages.addItemStage("infinity", <industrialforegoing:enchantment_invoker>);
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 26 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 26 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 27 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 28 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 29 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 30 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 31 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 31 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 31 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 36 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 36 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 36 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 15 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 15 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 12 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 12 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 12 as short}]}));
mods.ItemStages.addItemStage("infinity", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 12 as short}]}));
mods.ItemStages.addItemStage("infinity", <railcraft:anvil:*>);
mods.ItemStages.addItemStage("infinity", <railcraft:trade_station>);
mods.ItemStages.addItemStage("infinity", <railcraft:cart_trade_station>);
mods.orestages.OreStages.addReplacement("infinity", <railcraft:anvil:*>, <minecraft:stonebrick>);
mods.orestages.OreStages.addReplacement("infinity", <railcraft:trade_station>, <minecraft:stonebrick>);
