#Name: zzzblockdrops.zs
#Author: Austinsupercar

import mods.dropt.Dropt;

print("Initializing 'zzzblockdrops'...");

Dropt.list("first_list")

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone_pyrotech_fossil_ore:*", "undergroundbiomes:metamorphic_stone_pyrotech_fossil_ore:*", "undergroundbiomes:sedimentary_stone_pyrotech_fossil_ore:*", "pyrotech:fossil_ore"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(50))
          .items([<minecraft:bone>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(35))
          .items([<minecraft:coal>], Dropt.range(1, 3))
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(2))
          .items([<minecraft:dye:4>], Dropt.range(1, 4))
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<minecraft:redstone>], Dropt.range(1, 5))
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<geolosys:cluster:1>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<geolosys:cluster>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<minecraft:diamond>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<minecraft:sponge>])
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_nuclearcraft_ore:*", "undergroundbiomes:metamorphic_stone_nuclearcraft_ore:*", "undergroundbiomes:igneous_stone_nuclearcraft_ore:*", "undergroundbiomes:sedimentary_stone_tile.projectred.exploration.ore|3:*", "undergroundbiomes:metamorphic_stone_tile.projectred.exploration.ore|3:*", "undergroundbiomes:igneous_stone_tile.projectred.exploration.ore|3:*", "undergroundbiomes:sedimentary_stone_thermalfoundation_ore:*", "undergroundbiomes:metamorphic_stone_thermalfoundation_ore:*", "undergroundbiomes:igneous_stone_thermalfoundation_ore:*", "undergroundbiomes:sedimentary_stone_tile.for.resources.copper:*", "undergroundbiomes:metamorphic_stone_tile.for.resources.copper:*", "undergroundbiomes:igneous_stone_tile.for.resources.copper:*", "undergroundbiomes:sedimentary_stone_immersiveengineering_ore:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore:*", "undergroundbiomes:sedimentary_stone_mekanism_oreblock_1:*", "undergroundbiomes:metamorphic_stone_mekanism_oreblock_1:*", "undergroundbiomes:igneous_stone_mekanism_oreblock_1:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster:2>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(24))
          .items([<minecraft:redstone>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<minecraft:glowstone_dust>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_iron_ore:*", "undergroundbiomes:metamorphic_stone_iron_ore:*", "undergroundbiomes:igneous_stone_iron_ore:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_gold_ore:*", "undergroundbiomes:metamorphic_stone_gold_ore:*", "undergroundbiomes:igneous_stone_gold_ore:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster:1>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_mekanism_oreblock_2:*", "undergroundbiomes:metamorphic_stone_mekanism_oreblock_2:*", "undergroundbiomes:igneous_stone_mekanism_oreblock_2:*", "undergroundbiomes:sedimentary_stone_tile.projectred.exploration.ore|4:*", "undergroundbiomes:metamorphic_stone_tile.projectred.exploration.ore|4:*", "undergroundbiomes:igneous_stone_tile.projectred.exploration.ore|4:*", "undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.tin.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.tin.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.tin.name:*", "undergroundbiomes:sedimentary_stone_tile.nuclearcraft.ore.tin:*", "undergroundbiomes:metamorphic_stone_tile.nuclearcraft.ore.tin:*", "undergroundbiomes:igneous_stone_tile.nuclearcraft.ore.tin:*", "undergroundbiomes:sedimentary_stone_tile.for.resources.tin:*", "undergroundbiomes:metamorphic_stone_tile.for.resources.tin:*", "undergroundbiomes:igneous_stone_tile.for.resources.tin:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster:3>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(24))
          .items([<geolosys:cluster>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_immersiveengineering_ore_3:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore_3:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore_3:*", "undergroundbiomes:sedimentary_stone_tile.projectred.exploration.ore|5:*", "undergroundbiomes:metamorphic_stone_tile.projectred.exploration.ore|5:*", "undergroundbiomes:igneous_stone_tile.projectred.exploration.ore|5:*", "undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.silver.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.silver.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.silver.name:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster:4>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<geolosys:cluster:5>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(10))
          .items([<geolosys:cluster:1>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.lead.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.lead.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.lead.name:*", "undergroundbiomes:sedimentary_stone_immersiveengineering_ore_2:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore_2:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore_2:*", "undergroundbiomes:sedimentary_stone_tile.nuclearcraft.ore.lead:*", "undergroundbiomes:metamorphic_stone_tile.nuclearcraft.ore.lead:*", "undergroundbiomes:igneous_stone_tile.nuclearcraft.ore.lead:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(90))
          .items([<geolosys:cluster:5>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(10))
          .items([<geolosys:cluster:4>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_immersiveengineering_ore_1:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore_1:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore_1:*", "undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.aluminum.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.aluminum.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.aluminum.name:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(90))
          .items([<geolosys:cluster:6>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(10))
          .items([<geolosys:cluster>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_immersiveengineering_ore_4:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore_4:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore_4:*", "undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.nickel.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.nickel.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.nickel.name:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(90))
          .items([<geolosys:cluster:7>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(10))
          .items([<geolosys:cluster:8>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_tile.thermalfoundation.ore.platinum.name:*", "undergroundbiomes:metamorphic_stone_tile.thermalfoundation.ore.platinum.name:*", "undergroundbiomes:igneous_stone_tile.thermalfoundation.ore.platinum.name:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(90))
          .items([<geolosys:cluster:8>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<rockhounding_chemistry:chemical_dusts:29>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<geolosys:cluster:10>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_mekanism_oreblock:*", "undergroundbiomes:metamorphic_stone_mekanism_oreblock:*", "undergroundbiomes:igneous_stone_mekanism_oreblock:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(90))
          .items([<geolosys:cluster:12>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<geolosys:cluster:1>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<geolosys:cluster>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone_tile.nuclearcraft.ore.uranium:*", "undergroundbiomes:metamorphic_stone_tile.nuclearcraft.ore.uranium:*", "undergroundbiomes:igneous_stone_tile.nuclearcraft.ore.uranium:*", "undergroundbiomes:sedimentary_stone_immersiveengineering_ore_5:*", "undergroundbiomes:metamorphic_stone_immersiveengineering_ore_5:*", "undergroundbiomes:igneous_stone_immersiveengineering_ore_5:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<geolosys:cluster:9>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(24))
          .items([<geolosys:cluster:11>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<rockhounding_chemistry:chemical_dusts:48>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:red_granite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["advancedrocketry:stationbuilder"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:sign_q>])
        )
	)


	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:1"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:black_granite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:2"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rhyolite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:3"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:andesite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:4"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:gabbro_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:5"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:basalt_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:6"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:komatiite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_stone:7"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:dacite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:gneiss_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:1"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:eclogite_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:2"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:marble_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:3"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:quartzite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:4"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:blueschist_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:5"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:greenschist_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:6"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:soapstone_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_stone:7"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:migmatite_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:limestone_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:1"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:chalk_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:2"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:shale_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:3"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:siltstone_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:4"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:lignite_rock>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:5"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:dolomite_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:6"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:greywacke_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_stone:7"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:chert_rock>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:stone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_stone>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["minecraft:end_stone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_endstone>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["minecraft:stone:1"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_granite>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:stone:3"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_diorite>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:stone:5"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_andesite>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:sandstone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_sandstone>], Dropt.range(1, 3))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:red_sandstone"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_red_sandstone>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["minecraft:netherrack"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<contenttweaker:rock_netherrack>], Dropt.range(1, 3))
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["minecraft:gravel:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:3>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:2>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:1>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:flint>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_gravel:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:3>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:2>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:1>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:flint>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_gravel:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:3>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:2>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:1>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:flint>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_gravel:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:3>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:2>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:1>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:flint>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:sand:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<minecraft:reeds>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:material:17>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:5>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:4>], Dropt.range(1, 5))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:igneous_sand:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<minecraft:reeds>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:material:17>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:5>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:4>], Dropt.range(1, 5))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:metamorphic_sand:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<minecraft:reeds>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:material:17>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:5>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:4>], Dropt.range(1, 5))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["undergroundbiomes:sedimentary_sand:*"])
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<minecraft:reeds>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:material:17>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<pyrotech:rock:5>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(20))
          .items([<pyrotech:rock:4>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<forestry:peat>], Dropt.range(1, 5))
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:tallgrass:*"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<pyrotech:material:12>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:wheat_seeds>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<immersiveengineering:seed>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["minecraft:vine:*"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<pyrotech:material:12>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:wheat_seeds>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<immersiveengineering:seed>])
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["better_diving:seagrass_tall_top"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<pyrotech:material:12>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:wheat_seeds>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<immersiveengineering:seed>])
        )
	)
	
	.add(Dropt.rule()
		.matchBlocks(["better_diving:seagrass_tall_bottom"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<pyrotech:material:12>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(15))
          .items([<minecraft:wheat_seeds>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<immersiveengineering:seed>])
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["better_diving:sandstone_outcrop:*"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<geolosys:cluster:1>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<better_diving:gold>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<better_diving:lead>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<better_diving:silver_ore>])
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["better_diving:limestone_outcrop:*"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<minecraft:coal>], Dropt.range(1, 5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<geolosys:cluster>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<better_diving:titanium>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(25))
          .items([<better_diving:copper_ore>])
        )
	)

	.add(Dropt.rule()
		.matchBlocks(["better_diving:seagrass"])
		.addDrop(Dropt.drop()
			.selector(Dropt.weight(5))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(75))
          .items([<pyrotech:material:12>], Dropt.range(1, 3))
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<minecraft:wheat_seeds>])
        )
        .addDrop(Dropt.drop()
          .selector(Dropt.weight(5))
          .items([<immersiveengineering:seed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<minecraft:sapling>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:appleseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:oakseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:spruceseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:birchseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:jungleseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:acaciaseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:darkoakseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<dynamictrees:cactusseed>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<minecraft:snowball>])
        )
		  .addDrop(Dropt.drop()
          .selector(Dropt.weight(1))
          .items([<minecraft:sponge:1>])
        )
	);